### ISSUE TITLE
Update button in settings of AwesomeTTS broken

### ISSUE THREAD

**Issue by hy0merun** [AwesomeTTS/awesometts-anki-addon#100]
on v.1.16.00
under Tools - AwesomeTTS - Advanced

![Screenshot 2020-06-18 at 11 37 37](https://user-images.githubusercontent.com/67026243/85005055-94ce2e00-b158-11ea-86c2-6be9f7c94611.png)

**Comment by lucwastiaux** [comment]
Thanks for reporting. Note that updating through the Anki Addons screen (Tools -> Add-ons, Check for updates) should work though.

**Comment by lucwastiaux** [comment]
It turns out this update checker code is not required anymore after Anki 2.1, which has an addon updating mechanism. So this whole section in AwesomeTTS preferences can be removed.

**Comment by lucwastiaux** [comment]
I've disabled the update checking code since this is all handled by Anki as of 2.1.
