### ISSUE TITLE
Microsoft Azure TTS error

### ISSUE THREAD

**Issue by Mercu7io** [AwesomeTTS/awesometts-anki-addon#103]
Hello,
When i try to use Azure TTS, i always have this error, whatever the language I choose.
I setup my API key from Azure.
In azure my location for the ressource is : southcentralus .

Status code: 401 reason: Unauthorized voice: [Microsoft Server Speech Text to Speech Voice (he-IL, Asaf)] language: [he-IL subscription key: [----]]

Status code: 401 reason: Unauthorized voice: [Microsoft Server Speech Text to Speech Voice (fr-FR, Paul, Apollo)] language: [fr-FR subscription key: [-------------]]

Any idea how to make i works?
Thanks

**Comment by lucwastiaux** [comment]
Can you try to use eastus as the region?
I believe that's the problem. I'll try to make this configurable in the future.

**Comment by Mercu7io** [comment]
Thanks, it works with eastus !

**Comment by Mercu7io** [comment]
Sorry, It works in preview mode nut when i try to generate with the option adding audio to selected, i have the error:
---------------------------
Anki
---------------------------
The 1 note you selected has been processed. During processing, no notes were successfully updated.

The following problem was encountered:
Status code: 401 reason: Unauthorized voice: [Microsoft Server Speech Text to Speech Voice (he-IL, Asaf)] language: [he-IL subscription key: [-------------]] (1 time)

The following note(s) have failed:
'אֵין', 
---------------------------
OK   
---------------------------

**Comment by lucwastiaux** [comment]
Let me check a bit later, mayne that voice is only available in some regions. I can fix it for you if you give me a couple of days.

**Comment by Mercu7io** [comment]
Take your time, no problem
I works if i generate the sound one by one in the add card.
It only failed for the batch mode ;)

**Comment by Mercu7io** [comment]
And thank you

**Comment by ingrandok** [comment]
I'm having the same Unauthorized voice issue. I moved my resource group to East US and I've tried a number of English and Japanese voices. All have failed to preview.

**Comment by kingrando** [comment]
I'm having the same Unauthorized voice error. I've tried a number of English and Japanese voices. All have failed to preview. I confirmed my resource group was setup in East US as well.

**Comment by lucwastiaux** [comment]
@Mercu7io I've added support for choosing the region in https://github.com/AwesomeTTS/awesometts-anki-addon/blob/master/awesometts/service/azure.py 
However that doesn't explain why you can't use your eastus key in batch mode, only in preview mode.

@kingrando could you email me your azure key at awesometts@airpost.net ? I'm only going to use it a couple of times to test, and you can regenerate it afterwards.

**Comment by Mercu7io** [comment]
@lucwastiaux It seems the problem came from ms Azure.
I tried again this morning and it works.
I just saw that they had separate TTS from CognitiveService. Now there is a new service: "SpeechServices" that include TTS.
Maybe that's why they had problem yesterday

**Comment by lucwastiaux** [comment]
Another thing that could happen is that awesometts requests a "token" on the first run, and keeps using it throughout your anki session, and it may become invalid after some time. Let me look into it. If you get that error again, you could try restarting anki.

**Comment by Mercu7io** [comment]
> Another thing that could happen is that awesometts requests a "token" on the first run, and keeps using it throughout your anki session, and it may become invalid after some time. Let me look into it. If you get that error again, you could try restarting anki.

I sent you my API key if you want to test

**Comment by Mercu7io** [comment]
You're right, i need to restart Anki every 20 request (i use free TTS)

**Comment by lucwastiaux** [comment]
@kingrando @Mercu7io if you're interested, i'm making my Azure, Google and Forvo keys available to paid patreon fans: https://www.patreon.com/lucw that way you can experiment with a number of voices without having to sign up for a multitude of services.

**Comment by lucwastiaux** [comment]
@Mercu7io @kingrando I just released a fix in v1.18 where the Azure authorization token is refreshed every 5mn. I believe this should prevent this "unauthorized voice" message. Please give it a try.
