### ISSUE TITLE
Drop-down menu for 'Voice' does not work (Google Cloud Text-To-Speech)

### ISSUE THREAD

**Issue by ryanjcain** [AwesomeTTS/awesometts-anki-addon#104]
Hello!

I am trying to use the service with google cloud text-to-speech waveform, but the dropdown menu does not let me select a language. I have tried restarting Anki and my mac several times and other trouble shooting (and all of the other drop down menus work fine) but for some reason it will not let me select a voice from this specific dropdown menu.

I am running:
**AwesomeTTS v1.17.0**
**MacOS Catalina 10.15.4**

I would appreciate any help thank you!

**Comment by lucwastiaux** [comment]
I've seen this issue reported by a reddit user. Does this dropdown work for other services ?

**Comment by lovac42** [comment]
This maybe related with a work around. Linking this: https://github.com/kelciour/awesometts-anki-addon/issues/19

**Comment by lucwastiaux** [comment]
FYI I have a report from a reddit user that removing some unused voices allows the dropdown to work properly. So the bug looks like it is related to the large number of items inside that dropdown (more than 240).

**Comment by lucwastiaux** [comment]
@ryanjcain @lovac42 I just made a commit which i'm hoping will fix the issue: edd363af11eb3627649208cc1433395c356ca854 ( grab the latest version of awesometts/gui/base.py). It reduces the maximum number of items displayed.
could I ask one of you to try it on Mac OS X catalina ?

**Comment by ryanjcain** [comment]
@lucwastiaux 
Hey, thank you for responding so quickly, I will add these changes now and let you know if I can get it to work on Catalina.

**Comment by lucwastiaux** [comment]
@ryanjcain did you get a chance to test this? I'm eager to make a release if it does fix the issue.

**Comment by lucwastiaux** [comment]
I've release the above fix in v1.18. I'd like to get some feedback from Mac OS X catalina users on whether this fixes the issue.

**Comment by ryanjcain** [comment]
@lucwastiaux Hello again! I am very sorry for not checking this out sooner, something came up with my work. I downloaded the latest patch and it all seems to be working now! Thank you for getting out such a quick fix, I am sure the community will appreciate being able to use the Google waveform audio generations! :D

**Comment by ryanjcain** [comment]
@lucwastiaux Hmmm this could be something I messed up on my end because I am still investigating, but with the latest patch I am getting this error when trying to add audio to my cards:

`Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-05 11:24:27
Add-ons possibly involved: ⁨AwesomeTTS - Add speech to your flashcards, MIA Japanese⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 31, in cmd
  File "aqt/webview.py", line 97, in _onCmd
  File "/Users/ryanjcain 1/Library/Application Support/Anki2/addons21/278530045/main.py", line 386, in prevBridgeReroute
    ogAnkiWebBridge(self, cmd)
  File "aqt/webview.py", line 500, in _onBridgeCmd
  File "/Users/ryanjcain 1/Library/Application Support/Anki2/addons21/278530045/main.py", line 318, in bridgeReroute
    ogReroute(self, cmd)
  File "aqt/editor.py", line 378, in onBridgeCmd
  File "/Users/ryanjcain 1/Library/Application Support/Anki2/addons21/1436550454/awesometts/gui/common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "/Users/ryanjcain 1/Library/Application Support/Anki2/addons21/1436550454/awesometts/gui/generator.py", line 670, in __init__
    super(EditorGenerator, self).__init__(
  File "/Users/ryanjcain 1/Library/Application Support/Anki2/addons21/1436550454/awesometts/gui/base.py", line 243, in __init__
    super(ServiceDialog, self).__init__(*args, **kwargs)
  File "/Users/ryanjcain 1/Library/Application Support/Anki2/addons21/1436550454/awesometts/gui/base.py", line 77, in __init__
    super(Dialog, self).__init__(parent)
RuntimeError: wrapped C/C++ object of type AddCards has been deleted
`

This could be something cause by another one of my plugins, but I was unable to trouble shoot the issue directly.

**Comment by lucwastiaux** [comment]
This happens when you try to add sounds one by one to new cards as you're adding those cards, correct? I think someone else reported a similar issue but I wasn't able to track it down yet. 
Can you try batch generation?

**Comment by lucwastiaux** [comment]
@ryanjcain can you disable MIA Japanese and try again? From the stack trace it looks like it's playing a role on this bug.

**Comment by ryanjcain** [comment]
@lucwastiaux Hello again, yeah you are right. It worked without MIA add-on. After reinstalling MIA and restarting though both plugins seem to be working. 

Thanks again for being so active developing such a useful tool for everyone :D

**Comment by lucwastiaux** [comment]
@ryanjcain thank you, and please leave a review if you feel satisfied!
