### ISSUE TITLE
Google Translate (Inuktitut) Broken

### ISSUE THREAD

**Issue by marbuljon** [AwesomeTTS/awesometts-anki-addon#105]
Hi, it seems Google Translate for Inuktitut is broken. I've tried "Inuktitut (iu)" across several different days and each time it fails in both the preview and the actual generation, with the error:

"No response for web request".

Other languages from Google Translate seem to be working.

**Comment by lovac42** [comment]
Inuktitut was removed from gtts and Igbo was added, but w/o voice support.
![image](https://user-images.githubusercontent.com/42665127/85905176-b4a8c600-b7d8-11ea-9d69-b923614c30e0.png)

Some of these listed voices are old from 2.0, perhaps it's time to update the list.

**Comment by marbuljon** [comment]
Oh darn, well that answers that question. I'll hope that the Greenlandic TTS from my other post gets integrated or something then (Inuktitut and Greenlandic are basically dialects of each other). I'll close this issue!
