### ISSUE TITLE
Please help with Regex. Make first word after linebreak start with uppercase

### ISSUE THREAD

**Issue by happycamper78** [AwesomeTTS/awesometts-anki-addon#108]
Hi, can you please help me with regex syntax for the Advanced Text Configuration in Awesome TTS?
I want each first word after a new line break to start with an upper case. For example, if after a line break the first word of the new line is 'apple', I want the word to be 'Apple'.
What regex syntax do I need to insert into the add-on? I've tried \n(?=[a-z]) → \n(?=[A-Z]) but it's not working. Anyone who is good a regex can you please help me?

**Comment by lucwastiaux** [comment]
Please include an exact example.

- what is the exact content of the source field ?
- what exactly do you expect on the audio output ?

**Comment by happycamper78** [comment]
Hi, thank you for your quick reply. My cards have normal text and bullet point lists. Not every bullet point list starts with a capital letter at the first word, which shortens the pause before that bullet point in the pronounciation. Therefore, by changing the first lowercase letter of a word in a new line to an uppercase letter, the pause will be longer. This is the only reason I'm doing this. Here is a link to a screenshot - [https://www.dropbox.com/s/1f7e7volk3k64c8/Screen%20Shot%202020-07-01%20at%2012.49.22%20pm.jpg?dl=0](url) the text on the front of the card shall be converted to the text on the back of the card before being converted to audio (you will see that every new line starts with a capital letter now). This way, the pause between each new line will be equally long. Please let me know if this doesn't make sense. Thank you so much for your help :)

**Comment by happycamper78** [comment]
What I'm looking for is the syntax I can enter in these fields [https://www.dropbox.com/s/b49enkhtetvfor8/Screen%20Shot%202020-07-01%20at%2012.40.07%20pm.jpg?dl=0](url)

**Comment by lucwastiaux** [comment]
From a quick research, changing the case using only a regular expression is not possible in python. This would mean what you are asking for can't accomplished using this functionality of AwesomeTTS. My recommendation would be to try to find an addon (or write some code) that can transform your card content into something suitable for text to speech processing, then run AwesomeTTS on those fields.

**Comment by lucwastiaux** [comment]
as I mentioned, I don't think this is solvable directly in AwesomeTTS. If fixing this is very important to you, I suggest you try getting someone to write a piece of custom code for you in exchange for payment. If you're interested in discussing this idea, you can contact me at awesometts@airpost.net

**Comment by happycamper78** [comment]
Hi, thank you! :) In the meantime I've tried a few different regex formulas

(?<=\<li>)([a-z]) replace with \U$1
(?<=\<li>)([t]) replace with T (to work on individual characters)
\<li>t replace with <li>T (to work on individual characters and replace the <li> tag with it)

The above didn't work, this may be a Python limitation, as you have mentioned.

However, what worked for me was this regex syntax:

**Comment by lucwastiaux** [comment]
Great that you found a solution ! I commend you for your persistence !
