### ISSUE TITLE
Feature suggestion: Context menu item: "Say <selected text> using <preset>..."

### ISSUE THREAD

**Issue by brownbat** [AwesomeTTS/awesometts-anki-addon#110]
I'm coming from [AwesomeTTS (Google Cloud Text-to-Speech) (unofficial)](https://ankiweb.net/shared/info/814349176), really appreciate this main add on getting picked back up by a team.

One feature the unofficial version had that I found very useful was the context menu item when highlighting text on the back of the card, "Say (highlighted text) using (preset)..."

I have been doing some transcription to train my ear, and it's useful to hear even my incorrect typed answers read by the TTS for comparison.

I'm not sure if this is the same code base, but that option's just not activated with your add on, or if it's something that was developed only in the unofficial add on and hasn't made it over, or if it's just something wrong with my install.

**Comment by lucwastiaux** [comment]
To clarify, you would use this when using cloze deletion ?
do you happen to have a screenshot of the old feature ?

**Comment by brownbat** [comment]
I'm not using cloze deletion. I have some cards where the front plays Korean audio (hidden) with a type:English box. The back has the correct (visible) Korean writing.

In the below, I typed 군저 (~gunjeo) when the correct answer was the very similar 근처 (~geuncheo). With the unofficial branch, I could hear how the highlighted text (what I originally typed) sounds, and compare it side-by-side with the given answer by hitting F3.

![image](https://user-images.githubusercontent.com/26754/86511394-b1a86980-bdc6-11ea-9883-cf55497a0824.png)

**Comment by lucwastiaux** [comment]
That feature is available in the current version of AwesomeTTS. Can you tell me which version you're running ?
![screenshot](https://i.imgur.com/QNZNZ7Q.jpg)

**Comment by brownbat** [comment]
Oh, that's unexpected. I was on 1.17. I upgraded to 1.18, I disabled all my other add ons, and restarted Anki.

Still only getting the one drop down option, not sure why:

![image](https://user-images.githubusercontent.com/26754/86539055-cfa9c300-bec7-11ea-828e-25b3a7443d89.png)

**Comment by lucwastiaux** [comment]
Do you have some presets saved in awesometts?

**Comment by brownbat** [comment]
Aha. I had my Google API key loaded, but didn't realize I lost my presents when I moved back to the official version. 

Sorry about that! Will close. Thanks for talking me through this one.
