### ISSUE TITLE
Adding Additional Vietnamese TTS Services?

### ISSUE THREAD

**Issue by kuph16** [AwesomeTTS/awesometts-anki-addon#113]
Would it be possible to add these two Vietnamese TTS services to AwesomeTTS? 

[Option 1](https://fpt.ai/tts#) 
[Option 2](https://vbee.vn/)

They both feature a greater variation of accents (current supported services only offer Northern accent voice files), which may be helpful to those learning Vietnamese in other accents. Thank you!

**Comment by lucwastiaux** [comment]
OK I can try to take a look this weekend!

**Comment by lucwastiaux** [comment]
@kuph16 I added support for FPT.AI Vietnamese TTS. Can you help me test it ? For the second service as I mentioned, we'll need a financial contribution for the API key.

**Comment by lucwastiaux** [comment]
@kuph16 support for FPT.AI is in AwesomeTTS 1.20, just released

**Comment by lucwastiaux** [comment]
@pan-asian-wok should be fixed in the next release

**Comment by lucwastiaux** [comment]
@pan-asian-wok the voice has been fixed in v1.21, please check.

**Comment by pan-asian-wok** [comment]
@lucwastiaux The name of the voice is correct now. Thank you again for all your hard work!

**Comment by lucwastiaux** [comment]
@pan-asian-wok please remember to leave a good review on the addon page: https://ankiweb.net/shared/info/1436550454
