### ISSUE TITLE
Keyboard shortcut in note editor not configurable

### ISSUE THREAD

**Issue by hy0merun** [AwesomeTTS/awesometts-anki-addon#114]
There is a issue with the shortcut in the note editor. Since I want to use the built-in Latex shortcuts which have the same shortcut as AwesomeTTS (Command+T), I changed the shortcut for TTS for **note editor** to something else. However, when I press Command+T in the note editor, it still opens the **Config-Window** of AwesomeTTS.
 My assumption was that the program just takes the shortcut for the main window (the top one in the TTS config, even when being in the note editor, which turned out to be the case.

So obviously, the shortcut on the bottom ("To generate single MP3 in the note editor*, strike {Shortcut}") does not work, at least on MacOSX. 

![Screenshot 2020-07-10 at 14 13 43](https://user-images.githubusercontent.com/67026243/87153778-4d027880-c2b8-11ea-80ed-b2789a6f2ea2.png)

**Comment by lucwastiaux** [comment]
I'm not able to reproduce this bug on Linux, the shortcut I assigned for "To generate single MP3 in the note editor" is working correctly. Does the problem persist after a restart ?

**Comment by hy0merun** [comment]
When I posted this it didn't work even after restart, but now it somehow does.
This can be closed now, thanks.
