### ISSUE TITLE
Missing voices from Microsoft Azure

### ISSUE THREAD

**Issue by Kytanm** [AwesomeTTS/awesometts-anki-addon#116]
There are many missing neural voices from Microsoft Azure. I'm interested in pl-PL-ZofiaNeural, but checking the Voice list I saw that many other languages also lack the neural voices that are listed in https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#text-to-speech

**Comment by lucwastiaux** [comment]
Looks like Azure added tons of new voices, this is excellent news. Thanks for reporting this. I updated the voice list, it'll be in the next release, or you can download the latest https://github.com/AwesomeTTS/awesometts-anki-addon/blob/master/awesometts/service/azure.py if you need it immediately. The polish neural voice is there now.

**Comment by lucwastiaux** [comment]
@Kytanm the voice list has been updated in AwesomeTTS 1.20, just released.

**Comment by lucwastiaux** [comment]
@Kytanm if this issue was fixed to your satisfaction, please leave a review on the addon page; https://ankiweb.net/shared/info/1436550454
