### ISSUE TITLE
When trying to add On-The-Fly TTS tag to template I get this exception (has no attribute 'front')

### ISSUE THREAD

**Issue by eesposito** [AwesomeTTS/awesometts-anki-addon#119]
Anki 2.1.30 (06a69c25) Python 3.8.1 Qt 5.12.6 PyQt 5.12.3
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-09 10:16:07

Caught exception:
Traceback (most recent call last):
  File "D:\Anki\addons21\1436550454\awesometts\gui\templater.py", line 205, in accept
    target = getattr(tform, now['templater_target'])
AttributeError: 'Ui_Form' object has no attribute 'front'

**Comment by lucwastiaux** [comment]
What does your front card template look like ?

**Comment by jaredagordon** [comment]
I have the same issue-- this is what one of my card templates look like:

![image](https://user-images.githubusercontent.com/60485584/90629808-f872e700-e1ed-11ea-93f4-12c84a4a3922.png)

**Comment by lucwastiaux** [comment]
@jaredagordon where is your use of the TTS tag?

**Comment by mariuszmatusiak** [comment]
+1.
I've got the same issue, though I try to add cards for Japanese.
![otf tts](https://user-images.githubusercontent.com/15185649/91086310-0b9f1000-e64f-11ea-8ee9-f5ef38ae9aa5.png)

**Comment by lucwastiaux** [comment]
same bug as #121

**Comment by lucwastiaux** [comment]
this will be fixed in 1.22, if you can't wait, grab the latest templater.py: https://github.com/AwesomeTTS/awesometts-anki-addon/blob/master/awesometts/gui/templater.py

**Comment by lucwastiaux** [comment]
@eesposito @jaredagordon  this has been fixed in AwesomeTTS 1.22. Please leave a review on the addon page if you're satisfied with the bugfix: https://ankiweb.net/shared/info/1436550454
