### ISSUE TITLE
Randomizing <tts> voice?

### ISSUE THREAD

**Issue by yaoberh** [AwesomeTTS/awesometts-anki-addon#120]
Is it possible to randomize the tts voice for let's say Google Cloud tts? A random voice in japanese, for example. I don't know if this can be scripted or if it's even possible.

**Comment by lucwastiaux** [comment]
did you try using groups of service presets ? Described here: https://ankiatts.appspot.com/usage/groups

**Comment by lucwastiaux** [comment]
closed for inactivity, feel free to re-open
