### ISSUE TITLE
Streaks in group with random

### ISSUE THREAD

**Issue by brownbat** [AwesomeTTS/awesometts-anki-addon#122]
The current randomization of voices in a group can lead to long streaks of one voice over and over. (I have a group of four voices and I got the same voice eight times in a row.)

So I think it might be sometimes missing the call to shuffle or random? I can't rule out that it's just effectively randomizing presents and I was getting streaky results.

You might want to tune the algorithm so that the previously played option has lower weight, lower likelihood of coming up. It will make it "feel" more random, even though it would be technically less random. 

This is the same sort of compensation randomized playlists in music players have to use, to avoid the perfectly natural random occurrence of hearing the same song 3-5 times in a row.

One big impact would that you would be able to test your randomization code more easily, because long streaks would really pop out as something wrong.

Just an idea, the groups are working great overall. Thanks for all your work on this!

**Comment by lucwastiaux** [comment]
what about just cycling through all of the voices ?

**Comment by brownbat** [comment]
Sure, not using random would be a workaround.

So maybe you want to tune the shuffle long term to have more human (ie, biased) values, maybe you don't, either is a reasonable call.

If you do, it looks like Python 3.6 added random.choices() that accepts a list of weights.

So the simplest way I can think of would be:

1) build a dictionary mapping each voice to a weight, initialized to all 1s
2) when you play a voice, if voice[weight] == 1, increment all the other weights
3) If you play voice and voice[weight] > 1, decrement that voice[weight]

Then when you pick a voice just call random.choices() with the list of all the current weights.

The probabilities aren't like beautifully symmetrical in all cases or anything, but that's the simplest and cheapest way I could think of to smooth things out slightly.

The UX of randomization is somewhat cosmetic though, wouldn't blame you at all if you back-burnered this.

**Comment by brownbat** [comment]
For the last few weeks I've just been cycling through all the voices. That actually works great, you were right. I'm gonna close this one out...

**Comment by lucwastiaux** [comment]
Ah so you redefined your groups to just cycle through the voices?

**Comment by brownbat** [comment]
Yeah, working great, was a great suggestion.
