### ISSUE TITLE
Help button in AwesomeTTS: Configuration Window goes nowhere

### ISSUE THREAD

**Issue by jcsjcs13** [AwesomeTTS/awesometts-anki-addon#124]
Hi
When I press the help button in the "AwesomeTTS: Configuration" window, the browser greets me with a 404 error.
The page referenced is: https://github.com/AwesomeTTS/awesometts-anki-addon/config/advanced
Thank you for bringing AwesomeTTS to life again. It's such a useful tool.

**Comment by lucwastiaux** [comment]
Thank you, i'm going to redirect htis to the github wiki, which will allow community edits.
