### ISSUE TITLE
V1.22 and V1.21 seem broken

### ISSUE THREAD

**Issue by jcsjcs13** [AwesomeTTS/awesometts-anki-addon#125]
I'm not sure what it is, but both V1.22 and V1.21 (auto-upgraded) result in this error message when pressing "ctrl-T" to add audio:
`Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.32 (dee7d45d) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-01 20:08:20

Caught exception:
Traceback (most recent call last):
  File "aqt/editor.py", line 342, in checkFocus
TypeError: launch() missing 1 required positional argument: 'editor'
`
I had to manually download V1.20 and re-install this older version to be able to use the plugin.

**Comment by lucwastiaux** [comment]
What happens when you launch awesometts from the menu?

**Comment by cereska** [comment]
Actually I'm facing the same issue. When adding a new note, when I'm in the target field and press ctrl + T, I get the same:

Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-03 15:13:55

Caught exception:
Traceback (most recent call last):
  File "aqt\editor.py", line 342, in checkFocus
TypeError: launch() missing 1 required positional argument: 'editor'

and the addon window doesn't show up. 

To answer your question, when I lauch awesometts from the menu, at least in my case, there is this other html parser error I logged separately. Do you need any further details for this one?

**Comment by jcsjcs13** [comment]
Hi  lucwastiaux
Thank you for your reply.
I'm not sure how "launching awesometts" from the menu works.
There's "AwesomeTTS" below the Tool menu, which brings me to the Configuration. That's working fine.
In the card browser there's "Add audio to selected", which also seems to work fine.
There's no menu in the "Add" dialog. I can only press "ctrl-T" which is failing as described.

**Comment by lucwastiaux** [comment]
Add audio to selected is what I mean. I guess only the keyboard shortcut is broken?

**Comment by lucwastiaux** [comment]
@jcsjcs13 @cereska should be fixed in 1.23, if you need it right now, grab the latest awesometts/__init__.py
