### ISSUE TITLE
HTML parser error when trying to add audio to notes

### ISSUE THREAD

**Issue by cereska** [AwesomeTTS/awesometts-anki-addon#126]
Hi, 
I've been getting following error since (I think) version 1.20 of the plugin, currently on 1.22.  It shows up every time I open the plugin window to add an audio to a card. It doesn't stop me from adding the audio in the end, but it's getting slightly annoying over time, hope you can take a look what the root cause is. It was occurring on Anki version 2.1.22 and now on 2.1.33. The TTS used was Azure. Please let me know if you need more info.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-02 05:48:50

C:\Users\[username]\AppData\Roaming\Anki2\addons21\1436550454\awesometts\text.py:285: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 285 of the file C:\Users\[username]\AppData\Roaming\Anki2\addons21\1436550454\awesometts\text.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(text)

**Comment by lucwastiaux** [comment]
Just to confirm, this happens when you use Azure? Do you use any other services?

**Comment by cereska** [comment]
The error message shows as soon as the "Add TTS Audio to note" window is opened (e.g. by pressing addon icon in add new note window, with the target field focused), so before I am able to change the TTS engine. 
I mostly use Azure, whenever the "Add TTS Audio to note" is opened, it defaults/populates form fields with my Azure preset, despite other presets present.

**Comment by lucwastiaux** [comment]
Would you be able to record a screen capture ?

**Comment by cereska** [comment]
Sure, here you go:
[2020-09-02_14h13_36v2.zip](https://github.com/AwesomeTTS/awesometts-anki-addon/files/5162639/2020-09-02_14h13_36v2.zip)

(uploading zipped mp4 as the quality of a gif was quite bad)

**Comment by lucwastiaux** [comment]
OK perfect, thank you, give me a bit of time to look into this.

**Comment by cereska** [comment]
Of course, take your time :)

**Comment by lucwastiaux** [comment]
should be fixed in 1.32, if you can't wait, grab the latest awesometts/text.py
