### ISSUE TITLE
Add new voices for Oddcast

### ISSUE THREAD

**Issue by bgx90** [AwesomeTTS/awesometts-anki-addon#128]
Looking at the [Oddcast TTS demo page](https://www.oddcast.com/ttsdemo/index.php), I see that there are many more voices available for Japanese than what AwesomeTTS offers in its voice selection. I guess that these are new additions. I don't know if this is the case for other languages since I only use the Japanese voices, but I would not be surprised if they had additional voices as well. Would it possible to add these other voices (the Japanese ones at least) to AwesomeTTS?

**Comment by lucwastiaux** [comment]
Done, it'll be in 1.23. If you're willing to test, please grab the latest oddcast.py: https://github.com/AwesomeTTS/awesometts-anki-addon/blob/master/awesometts/service/oddcast.py
If this solves your issue in a satisfactory way, please leave a positive review on the addon page.

**Comment by lucwastiaux** [comment]
also, reminder that paid Patreon fans have access to community shared keys for high quality neural network voices from Google and Azure, which includes Japanese voices. https://www.patreon.com/lucw

**Comment by bgx90** [comment]
Thanks, I tried it out and am able to generate mp3s with the new Japanese voices.  I'm on Debian Testing and the version of Anki in the repo is still at 2.1.15, so I can't test with the latest version of the AwesomeTTS addon. However, for anyone else using Anki 2.1.15 with an older version of AwesomeTTS, I can confirm that simply updating the file `~/.local/share/Anki2/addons21/1436550454/awesometts/service$ oddcast.py` (adjust the path per your operating system) with the new voice options works for getting the new voice options.

**Comment by lucwastiaux** [comment]
Thank you @bgx90, can I ask you to write a review on the add-on page?

**Comment by lucwastiaux** [comment]
Ah I see you did, thank you so much!
