### ISSUE TITLE
Oxford Dictionary needs more tests

### ISSUE THREAD

**Issue by Grelo4ka** [AwesomeTTS/awesometts-anki-addon#134]
Currently, the only test case for Oxford Dictionary is the `successful` word. Even though AwesomeTTS passes it without any issues, that's not the case for some of the other phrases. Currently, broken test cases not included in the tests:
- `baby buggy` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/baby-buggy
- `devastated` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/devastated
- `first-time` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/first-time
- `stuck` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/stuck_1 ([...]/stuck redirects to [...]/stuck_1 where the word is located)
- `vice versa` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/vice-versa (2 are available but AwesomeTTS can't find any of them)
- `hairdryer` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/hairdryer
- `settled` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/settled
- `shocked` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/shocked
- `fed up` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/fed-up
- `climate change` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/climate-change
- `sea level` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/sea-level
- `terrified` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/terrified
- `thrilled` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/thrilled
- `worn out` (en-GB and en-US) - https://www.oxfordlearnersdictionaries.com/definition/english/worn-out

**Comment by lucwastiaux** [comment]
Thanks, I will start to look into these over the next couple of days.
