### ISSUE TITLE
Requests to "register this language" on startup

### ISSUE THREAD

**Issue by brownbat** [AwesomeTTS/awesometts-anki-addon#139]
Every time I start up Anki for the morning since the latest update, I get this error:

````
---------------------------
Anki
---------------------------
AwesomeTTS: Language zh_CN (Chinese (Mandarin, simplified)) not configured for on-the-fly TTS, please add TTS tag in Card template editor to register this language.
---------------------------
OK   
---------------------------
````

I open the card template and ask ATTS to insert a field. It inserts exactly the same field as was there before, and says the language is now successfully registered. Reviewing works as expected (no errors) for that session.

Field inserted (for field "Character"): 
{{tts zh_CN voices=AwesomeTTS:Character}}

HOWEVER, if I shut down Anki and open it again, the error returns, and it asks me to register the language again.

So, my actions are: 

1. Reviewing (see error). 
2. Edit > Cards (see error again) > Add tts > Generate Using: Chinese (group) OR individual voice. 
3. Select correct language on right-hand side of dialog. 
4. See new message indicating language group is now registered to zh_CN.
5. Review as normal, no errors, seems successful.
6. Close and reopen Anki. 
7. Same error message appears when reviewing again.

This is on a Win 10 laptop running Anki v.2.1.35, with AwesomeTTS fully updated.

Thanks for your help and continued development.

**Comment by lucwastiaux** [comment]
OK I've gotten reports of the same thing. i'm on it. Please give me a bit of time.

**Comment by lucwastiaux** [comment]
I can confirm AwesomeTTS 1.25 had a bug where the language to preset association wasn't remembered across restarts. I believe I have now fixed this in AwesomeTTS 1.26. Could I ask you to give it a try and let me know how it goes ?

**Comment by lucwastiaux** [comment]
I wrote the following documentation which can potentially clarify certain things https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/On-the-fly-TTS

**Comment by brownbat** [comment]
Updating to 1.26, then removing the tag and re-adding the tag did work. Thanks!

I use the same tag on three decks, looks like I only had to re-add it to one deck to form the association linking a language and a group preset. 

A more explicit dialog that lets you set languages to presets would be nice for usability in the long run. But not a priority, this works great now.

Thanks for the really fast bugfixes!

**Comment by lucwastiaux** [comment]
I'm doing some large overhaul work in AwesomeTTS where the voices in each service will be clearly associated with a language. So in the future, specifying the language may be automatic. It will also allow filtering services/voices by language.

**Comment by brownbat** [comment]
> specifying the language may be automatic

That's going to be really cool, definitely the right way to do this long term.

One weird corner case you'll hit with that -- I currently use a mix of Mandarin and Taiwanese voices in my "Chinese" preset group, even though those would technically belong to different language codes. It gives me twice as many voices per field.

There probably aren't a lot of cases like that. Maybe some Arabic dialects are similar enough to group together, not sure.

**Comment by lucwastiaux** [comment]
AwesomeTTS will still allow you to mix mandarin simplified and mandarin Taiwan into a single group, but Anki Mobile and AnkiDroid may force you to choose one or the other.

**Comment by OctavianJulius** [comment]
It worked by changing "voice=" to "preset="
