### ISSUE TITLE
Support Anki 2.1

### ISSUE THREAD

**Issue by krassowski** [AwesomeTTS/awesometts-anki-addon#14]
Hi,

I have seen the text "AwesomeTTS only supports Anki 2.0.x. The add-on will not work with the newer Anki 2.1.x." and I wanted to ask for a reason of that - is this only lack of time or some technical issue in 2.1.x? Will you accept pull requests providing 2.1 support?

**Comment by krassowski** [comment]
@felixraumann?

**Comment by felixraumann** [comment]
only lack of time. I will accept pull requests!!

**Comment by krassowski** [comment]
I got the add-on working with Anki 2.1.

I added some integration tests (runned by py.test) and I can confirm that all services do work (except iSpeech - I do not know how to test it without API key). Also GUI and reviewing works (in my normal use cases, but there are many other to test).

The biggest drawback I encountered is lack of (list-add, arrow-up, arrow-down, editdelete) icons. We will (probably) need to deliver those within addon itself.

@felixraumann please look at my tests code; should I keep those or remove for PR? I would like to expand the test suite in future (before making the PR) to make sure that every use-case is covered. I can set-up Travis integration with help of someone having access to this repository.

For more, please check out my fork: https://github.com/krassowski/awesometts-anki-addon/tree/anki-2.1.

**Comment by krassowski** [comment]
I think that Anki 2.1 should be supported on another branch (or current branch should be branched into new master (for 2.1) and "old" "stable-2.0"). There are too many changes to support both versions with a single codebase easily (and it is possible to upload two versions of add-on to ankiweb now: one for Anki 2.0 and one for Anki 2.1). 

@felixraumann, what do you think? Against which branch should I create my PR?
@woj-tek, you thumbed-up this issue - please feel free to test, use and improve the 2.1 branch :)

**Comment by felixraumann** [comment]
the future is anki 2.1. I branched master to master-2.0 for anki 2.0. you can make your pull request based on master.

**Comment by felixraumann** [comment]
I think I can invite you so you can setup travis.

**Comment by felixraumann** [comment]
@krassowski I think you can add webhooks now for travis.

**Comment by krassowski** [comment]
Thank you, I joined. I managed to integrate travis on my [fork](https://travis-ci.org/krassowski/awesometts-anki-addon/builds/287744828) but it seems that the Travis did not caught up with me joining the organization yet. I tried making my membership public, sign out/sign in but it did not work. Some folks wrote it can take up to 24 hours so I hope I will be able to set-up webhooks soon.

**Comment by felixraumann** [comment]
yes, maybe travis has a cache.
can you do it throuh settings tab above?

**Comment by krassowski** [comment]
Apparently. It works now, I set-up the webhooks. I will send a PR soon.
