### ISSUE TITLE
The addon fails to load on Anki.

### ISSUE THREAD

**Issue by Alekssavin** [AwesomeTTS/awesometts-anki-addon#140]
I use Anki Version 2.1.13 (3ba55990), Qt 5.12.7 PyQt 5.13.1, OpenSuse Leap 15.2 distro.
First I tried installing the addon with Anki addon code to no avail. Then I downloaded the .addon file from github, installed it with Anki.
When I start Anki I get the following message:
`
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'AwesomeTTS':
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 80, in loadAddons
    __import__(dir)
  File "/home/aleksandr/.local/share/Anki2/addons21/awesometts/__init__.py", line 42, in <module>
    from . import awesometts  # noqa, pylint:disable=wrong-import-position
  File "/home/aleksandr/.local/share/Anki2/addons21/awesometts/awesometts/__init__.py", line 40, in <module>
    from .ttsplayer import register_tts_player
  File "/home/aleksandr/.local/share/Anki2/addons21/awesometts/awesometts/ttsplayer.py", line 11, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
`
I don't know what it means. Please, help me fixing the problem. Cheers.

**Comment by lucwastiaux** [comment]
Your anki version is very old, are you able to install 2.1.35? It's very easy, you just need to unzip it and run.

**Comment by Alekssavin** [comment]
I did that, successfully reinstalled the add-on with the code. Now it works well. Thanks!

**Comment by lucwastiaux** [comment]
You're welcome! If you feel happy with awesometts, please leave a review
