### ISSUE TITLE
Not reading 'un-clozed' text on a multiple cloze card

### ISSUE THREAD

**Issue by rumDMC** [AwesomeTTS/awesometts-anki-addon#143]
Using Anki version 2.1.26 and AwesomeTTS v1.26.0

When a card with multiple clozes is being read, the voice skips all closed words whether its the cloze being tested or not. 
Example:
Actual text when making card -  The {{c1::world}} has gone {{c2::nuts}}
What is shown on the card while reviewing - The ...... has gone nuts
What is read out loud - The ...... has gone ......

Is there a setting I'm missing?
![image](https://user-images.githubusercontent.com/63619599/97204022-f304c080-178b-11eb-8411-6d25b689e0b4.png)

**Comment by lucwastiaux** [comment]
Which field type did you select when inserting the TTS tag?

**Comment by rumDMC** [comment]
Text. I think this is what you're asking, if not let me know:

![image](https://user-images.githubusercontent.com/63619599/97240706-595a0500-17c5-11eb-9994-c7591f1004af.png)

**Comment by rumDMC** [comment]
I also can't find a way to have the card automatically read out. I have to press the play button each time I go to a new card. I noticed that there is a Playback tab in the configuration options in your screenshots, but I do not have that tab on my version (v26). Did I download the wrong version?

**Comment by lucwastiaux** [comment]
If you are you a cloze card type, the only available method is on the fly audio, the screenshot above suggests you are doing batch generation https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/On-the-fly-TTS

**Comment by rumDMC** [comment]
So when I try to go through the on the fly method I get an error message. It's when I am 'managing the note type' and select the TTS button on the bottom that I get this:
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-10-26 08:07:14

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Dylan M Cooper\AppData\Roaming\Anki2\addons21\awesometts\awesometts\gui\common.py", line 126, in _show
    self._instance.show()
  File "C:\Users\Dylan M Cooper\AppData\Roaming\Anki2\addons21\awesometts\awesometts\gui\templater.py", line 179, in show
    self.get_target_selected()
  File "C:\Users\Dylan M Cooper\AppData\Roaming\Anki2\addons21\awesometts\awesometts\gui\templater.py", line 165, in get_target_selected
    if self._card_layout.tform.front_button.isChecked():
AttributeError: 'Ui_Form' object has no attribute 'front_button'



Here's a picture of the set up:
![image](https://user-images.githubusercontent.com/63619599/97288551-5a6a5100-181c-11eb-8a76-7c129c5101b5.png)

**Comment by lucwastiaux** [comment]
You have to be on anki 2.1.28 at least. Anki introduced a breaking change in the template editor in that version. You may have gotten a warning when upgrading the add-on.

**Comment by rumDMC** [comment]
Okay, I thought that may be the issue.
Thanks so much for your help, I've made a few work-arounds to use the addon with all of my single cloze cards / basic cards. It really makes a huge difference.
Do you have a way I can make a donation to you?

**Comment by lucwastiaux** [comment]
So is it working for you now?
If you want to express your gratitude, you can leave a review here https://ankiweb.net/shared/info/1436550454
And if you're interested, patreon paid fans have access to all the premium TTS service API keys : https://www.patreon.com/lucw

**Comment by rumDMC** [comment]
It works on the cards with just 1 cloze, but I'm waiting for the Hoochie Mama addon to update before I can upgrade to Anki 2.1.35. But its amazing for the cards I can use it on. 

Awesome, I can do that. Thanks again, it's an amazing addon
