### ISSUE TITLE
[non-blocking][regression] Can't read multiple fields at once since last major update

### ISSUE THREAD

**Issue by Quezako** [AwesomeTTS/awesometts-anki-addon#144]
Hello,

Before, I was able to read multiple fields at once with TTS, but now, I have to put each field side by side and the reading is way less natural.
For instance:
```
{{tts ja_JP voices=AwesomeTTS:kana:Kanji1}}
{{tts ja_JP voices=AwesomeTTS:Particule}}
{{tts ja_JP voices=AwesomeTTS:Kanji2}}
```

Is there a way to read them in a single batch, like before?

**Comment by lucwastiaux** [comment]
What syntax allowed you to read multiple fields at once previously?

**Comment by Quezako** [comment]
<tts ...>
{field1}{field2}{field3}
</tts>

**Comment by lucwastiaux** [comment]
OK. and is batch generation an option for you ? I'll have to look into how to accomplish that. The change which switched to the {{tts}} tag was meant to be more compatible with Anki and Anki mobile apps. It doesn't support smoothly reading multiple fields together.

**Comment by Quezako** [comment]
Why not, yes. That could be a good idea!
Sure, I was wondering why such a change, but I think it was a good decision to make your addon more compatible.

Otherwise, maybe a syntax like that?
```
{{#tts ja_JP voices=AwesomeTTS}}
    {kana:Kanji1}
    {Particule}
    {kana:Kanji2}
{{/tts}}
```

**Comment by lucwastiaux** [comment]
Following the Anki framework for the TTS tag makes AwesomeTTS more future proof, with less code to manage, so less risk of bugs. There are cases like yours where unfortunately it doesn't work as well. Could you make your deck available and I can try to think of solutions ?

**Comment by Quezako** [comment]
Sure, here it is:
https://ankiweb.net/shared/info/1419539410

**Comment by lucwastiaux** [comment]
Are the different fields in different languages ? The deck you linked doesn't seem to have Kanji1, Kanji2, Particule, it only has Kanji ? I started downloading from ankiweb but it's super slow.

**Comment by Quezako** [comment]
Yes, they have slow servers lately, I don't know why.
There are 2 decks with many different cards, but I've only added TTS to the
Japanese words and sentences.

I am not the original author of the deck, but I've changed it to be
conversation oriented.

I have a more recent version of it, but I've already changed the TTS tags
to your new system, so I don't know if it could be of any use?
I can put it on Google drive if needed.


Regards,
Jonathan Mousserion

**Comment by lucwastiaux** [comment]
If you could share your exact version of the deck, that would be useful to me. Thank you.

**Comment by Quezako** [comment]
https://drive.google.com/file/d/1HiPpraAGdfviy89SbTWxvB3UkB8GXhFh/view?usp=sharing

**Comment by lucwastiaux** [comment]
OK give me a little bit of time. I will study possible solutions.

**Comment by Quezako** [comment]
Hello, is there any news?
It seems also that now, the Japanese TTS has troubles to read the sound "お" (o) at the beginning of some sentences.
Sometimes, this "o" is not pronounced.

I also had sometimes an error message about encoding for some monosyllabic words.
Unfortunately, I don't remember which one, but it happens sometimes.

**Comment by lucwastiaux** [comment]
Haven't had time to look into it yet but it's on my list. Which Japanese tts service are you referring to?

**Comment by Quezako** [comment]
Google service.
Do you advise me another one?


Regards,
Jonathan Mousserion

**Comment by lucwastiaux** [comment]
@Quezako i'm just now diving back into this. I have one question: {{tts ja_JP voices=AwesomeTTS:kana:Kanji1}} what exactly does the "kana" syntax do ? is this something provided by an addon ?

**Comment by Quezako** [comment]
Hello,

I think it is native recognition of ways of reading Japanese.
Kanji is reading the Chinese ideograms, but can sometimes read the wrong
pronunciation of it, because Kanji have multiple pronunciations.
Kana is reading the hiragana (Japanese syllabus) written over that Kanji
(called furigana), to be sure that it's reading the good pronunciation.
It is far from perfect, because there are many different intonations given
for different Kanji with the same prononciation, but at least it is
pronounced the good syllabus.

Here is an example :
本 : is a Kanji that can be pronounced "hon", "moto", etc.
ほん : is the kana for making the sound "hon".
本[ほん] : is the combination in anki to tell that this Kanji should be
pronounced "hon". If you use :furigana: it will write both the Kanji and
the hiragana on top of it, in little characters.
If you put :furigana: in TTS, it is not good, because it will pronounce
both the Kanji and the kana.
That's why only :kana: is good for TTS.


Regards,
Jonathan Mousserion

**Comment by lucwastiaux** [comment]
my question is which piece of code understands what to do when you put `:kana:`  in the TTS field ? that's the part i'm missing.

**Comment by Quezako** [comment]
I don't know.


Regards,
Jonathan Mousserion

**Comment by lucwastiaux** [comment]
Coming back to this, I'm starting work on the next version of AwesomeTTS which will have user-defined template support. I'm hoping to put together a beta version very soon.

**Comment by lucwastiaux** [comment]
FYI @Quezako I recently discovered that your use case is still possible. Here's how to do it:
First, insert the TTS tag as usual, which will register the association between the ja_JP locale and your preset:
```{{tts ja_JP voices=AwesomeTTS:JapaneseField1}}```
Then, manually edit this tag to this syntax:
```[anki:tts][ja_JP]{{JapaneseField1}} {{JapaneseField2}}[/anki:tts]```
then save the template.
Please give it a try , you should hear the two fields one after another in a single sound. Note that the author of Anki has indicated this is unofficial and may break one day, but I feel like it's still usable.

**Comment by Quezako** [comment]
wow! thank you very much! I may need that for another deck :)

**Comment by lucwastiaux** [comment]
No need to thank me, i've kind of left you hanging for a year on this. But I'm keen to fix it in AwesomeTTS 2.0 which I think you'll find interesting.

**Comment by luc-languagetools** [comment]
Hi, this is finally supported in Anki 2.1.50+, you can use the following syntax:
`[anki:tts lang=en_US hypertts_preset=Back_realtime_0 voices=HyperTTS]english: {{English}} notes: {{Notes}}[/anki:tts]`

you'll have to manually edit the TTS tag after AwesomeTTS adds it. Note that for most cases, I now recommend using HyperTTS, it's more modern and more user friendly.

**Comment by Quezako** [comment]
Thank you very much!
