### ISSUE TITLE
FPT.AI times out when requesting audio

### ISSUE THREAD

**Issue by estheon** [AwesomeTTS/awesometts-anki-addon#146]
When requesting audio from FPT.AI, I keep getting an error: "No response for web request." I created a new API key from the website itself, but I also get the same error. 

In addition, I used Command Prompt to "ping" the fpt.ai website, and I get the error "Request timed out" from all four packets sent.

What should be done to resolve this issue?

**Comment by lucwastiaux** [comment]
The next awesometts release will include a way to inspect the debug log,which will help troubleshoot such issues. Please give me a bit of time.

**Comment by lucwastiaux** [comment]
I took another look at this and I believe there's an issue with the FPT.AI service, on their side. the generated audio is still not available after many retries, this is not the expected behavior. let me try to get in touch with them

**Comment by lucwastiaux** [comment]
Looks like it's working now, @estheon can you confirm ?

**Comment by estheon** [comment]
Yes, it is working now. Thank you for checking!
