### ISSUE TITLE
The widget on deck browser is huge

### ISSUE THREAD

**Issue by z-gong** [AwesomeTTS/awesometts-anki-addon#147]
The TTS widget introduced in the recent version is nice! But the interface may need some tuning.

This is how it looks like on my 2560x1440 screen with 150 % scaling.

![image](https://user-images.githubusercontent.com/379616/97632011-2ec0b400-1a32-11eb-816c-37aa3d3ee2f9.png)

**Comment by lucwastiaux** [comment]
No worries I will refine it, thanks for reporting!

**Comment by lucwastiaux** [comment]
You can disable the widget for now in the options (under advanced) if it bothers you.

**Comment by lucwastiaux** [comment]
I made the width proportional, thanks.

**Comment by lucwastiaux** [comment]
If you feel sastisfied with this fix, please leave a review on https://ankiweb.net/shared/info/1436550454
