### ISSUE TITLE
On the fly tts playback error

### ISSUE THREAD

**Issue by yaoberh** [AwesomeTTS/awesometts-anki-addon#148]
Today's update broke it, worked fine before today.
AwesomeTTS: Could not play back 墻: None of the presets in this group were able to play the input text.

**Comment by lucwastiaux** [comment]
which operating system are you using ? awesomeTTS now has debug logging enabled

**Comment by lucwastiaux** [comment]
are you familiar with how to startup anki on the command line ? set env variable AWESOMETTS_DEBUG_LOGGING to "enable", then start anki.

**Comment by yaoberh** [comment]
Arch linux. I don't know how to launch it with that variable, can you give me the complete command?

**Comment by lucwastiaux** [comment]
export AWESOMETTS_DEBUG_LOGGING=debug; anki

then show me the output. this will explain to me what's going on.

**Comment by yaoberh** [comment]
Restarted anki and now it's working. Didn't write the command. Looks like it didn't close correctly last time. One new thing however is this text to speech box. Is this an intended feature?

![Screenshot_2020-10-30_12-47-37](https://user-images.githubusercontent.com/30667087/97726512-0c6c7c00-1aae-11eb-9ba1-daca019eef94.png)

**Comment by lucwastiaux** [comment]
yes this is the new widget , you can use it to quickly check pronounciation on words

**Comment by yaoberh** [comment]
Thanks!
