### ISSUE TITLE
Forvo sex field is required but API specifies optional

### ISSUE THREAD

**Issue by TiddlyWiddly** [AwesomeTTS/awesometts-anki-addon#154]
The plugin field in Forvo for "sex" has menu options for male and female, but the Forvo API has this as an optional field. This means that if you search for a pronunciation in male voice, but only a female exists, or vice versa, you have to make two calls to get any result at all. The best fix is probably to add "any" as a third option which makes the API call without sex at all and grabs whatever the first result is.

https://api.forvo.com/documentation/word-pronunciations/

**Comment by lucwastiaux** [comment]
Yes that makes sense, let me look into it

**Comment by TiddlyWiddly** [comment]
Created a pull request for this, but honestly, I had no idea what a pull request was before 10 mins ago. Let me know if I need to do something different to submit my changes properly.

**Comment by lucwastiaux** [comment]
Thanks for your pull requested, I merged it.
