### ISSUE TITLE
IBM Watson 403 error

### ISSUE THREAD

**Issue by yaoberh** [AwesomeTTS/awesometts-anki-addon#158]
This is the error I get with any/all the voices available in IBM Watson:

Cannot preview the input phrase with these settings.

Status code: 403 reason: Forbidden voice: [Api key goes here, I deleted it]

**Comment by lucwastiaux** [comment]
Did you get your API key from patreon ? or you have your own key ?

**Comment by yaoberh** [comment]
I got one from the ibm webpage. I chose the free tier.

**Comment by lucwastiaux** [comment]
OK, I believe it's due to the different endpoint, I'll have to make a change to allow supplying different endpoints. In the mean time you can edit the source code in Watson.py on your add-on folder

**Comment by lucwastiaux** [comment]
In AwesomeTTS 1.29, you can now enter an API URL, which I believe will solve this issue.
