### ISSUE TITLE
Error: unable to read this tag

### ISSUE THREAD

**Issue by alaskakw** [AwesomeTTS/awesometts-anki-addon#16]
Here's the error. Seems it is because I have a large amount of text on the card. Reducing the text on the card by half make the error message go away. I was unable to find any information on there being a limit (using on-the-fly) after about 10 minutes of searching. 

![image](https://user-images.githubusercontent.com/29007905/31319150-0406345a-ac13-11e7-851f-018810c2ed66.png)

**Comment by felixraumann** [comment]
yes, there is a 2,000 character limit.
