### ISSUE TITLE
Cannot select Wavenet for Spanish on Google Cloud TTS

### ISSUE THREAD

**Issue by ksslng** [AwesomeTTS/awesometts-anki-addon#162]
Hello,
on the Google Cloud website, one can try out the service and one can select a wavenet output for Spanish https://cloud.google.com/text-to-speech#section-11

Sadly, when I tried it in Anki, there is only Spanish (es-ES-Standard-A) I can select. There is a noticeable difference between the two generations.

I just saw that in the code, it's probably that the configuration is just missing, I'll try to see if I can fix it myself and create a pull request.

Thank you for creating this awesome plugin!

**Comment by lucwastiaux** [comment]
I think it's a matter of refreshing the voice list, I can do that for the next release. This an issue with AwesomeTTS, the voice list is baked into the addon, while as Google / Azure tend to update their voice list pretty often. You can do a quick fix by editing your version of googletts.py and adding the voice. Also, Azure has Neural Spanish voices.

**Comment by ksslng** [comment]
Thank you for the quick reply, I've updated the Google TTS list and created a PR.

**Comment by lucwastiaux** [comment]
Thank you, I merged the PR.

**Comment by lucwastiaux** [comment]
Please note, I re-organized the way voices are displayed in the google dropdown. I also added a script which allows refreshing the voice list more easily. If you feel satisfied with this fix, please leave a review on here: https://ankiweb.net/shared/info/1436550454
