### ISSUE TITLE
how to restrict google api key?

### ISSUE THREAD

**Issue by srghma** [AwesomeTTS/awesometts-anki-addon#164]
you write

> Your API key should be restricted to _Cloud Text-to-Speech API _ For more information please see - https://cloud.google.com/docs/authentication/api-keys#creating_an_api_key

https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Google-Cloud-Text-to-Speech

what type of restriction do you mean?

![Screenshot](https://user-images.githubusercontent.com/7573215/103267911-4d541480-49bb-11eb-88e9-4351001b2113.png)

**Comment by lucwastiaux** [comment]
If it's your own API key, I wouldn't worry about it, as long as you don't share it with anyone. Just keep in mind it should be private, because people can effectively spend your money if they get ahold of your API key.
