### ISSUE TITLE
Microsoft Azure API Key Changes

### ISSUE THREAD

**Issue by MarleneMayr** [AwesomeTTS/awesometts-anki-addon#165]
The following wiki page changed: [Microsoft Azure Text to Speech](https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Microsoft-Azure-Text-to-Speech)
Microsoft extracted speech from their cognitive services. So now you just have to have for example a student account and can use the free tier for their speech services. Then the steps are as follows:
1. Create an account on https://portal.azure.com
1. Create a _Subscription_ which will have your billing information
1. Create a _Resource Group_ in _East US_
1. Create a _Speech Service_ entry
1. In your _Speech Service_ entry, your API key can be found under Resource Management -> Keys and Endpoint

**Comment by lucwastiaux** [comment]
Thanks, I updated the wiki page !
