### ISSUE TITLE
Azure - Chinese (Taiwanese Mandarin) unsupported voice

### ISSUE THREAD

**Issue by PQTran** [AwesomeTTS/awesometts-anki-addon#168]
Hello, I saw in the wiki to create a ticket for unsupported voices here. This is the error message I encounter for the 3 selected voices:

![Screenshot from 2021-01-11 20-13-03](https://user-images.githubusercontent.com/11433441/104268928-0c3a2500-54d0-11eb-8e22-8876ec91a951.png)

![Screenshot from 2021-01-11 20-13-49](https://user-images.githubusercontent.com/11433441/104268934-0e03e880-54d0-11eb-8575-a69c9a119aaa.png)

**Comment by lucwastiaux** [comment]
i'm able to use these voices and even added an automated test for them, they seem to work correctly. Which region is your azure key for ? My region is 'eastus'.

**Comment by PQTran** [comment]
Hi @lucwastiaux, thanks for the quick response. I was getting strange behaviour earlier, where the audio sample would work with Yating, but not HsiaoChen (both Chinese - Taiwanese Mandarin voices).


I was having weird behaviour involving: api-key allowing audio to be previewed for one chinese (taiwanese mandarin) voice, but not another.

I recreated the

**Comment by PQTran** [comment]
one thing to mention, I originally tried westus. However, I made sure the setting in awesometts and the azure instance were both the same settings.

**Comment by lucwastiaux** [comment]
Your API key is tied to an instance, the azure portal should be able to tell you exactly which region to use.

**Comment by PQTran** [comment]
After investigation, it looks like azure cognitive service hosted on westus is a different version from eastus. This affects the offered voices (west: 80, east: 200).

source:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech

**Comment by lucwastiaux** [comment]
Good find, thank you !

**Comment by lucwastiaux** [comment]
Note that if you become a paid fan on Patreon (https://www.patreon.com/lucw), you get access to keys for Google, Azure, Naver, Watson, with plenty of mandarin voices to choose from.
