### ISSUE TITLE
Forvo feature not working (not a computer programmer plz help)

### ISSUE THREAD

**Issue by brothamanben** [AwesomeTTS/awesometts-anki-addon#170]
Just got a Forvo API, put it in and it is not working. I keep getting this error, worked yesterday

![image](https://user-images.githubusercontent.com/68020961/105872490-722cbd80-6035-11eb-9f14-358ed8ffa4e7.png)

**Comment by brothamanben** [comment]
update: i think it’s because the api url is wrong, it should be this but i don’t know how change it , since it is in a drop down menu http://apicommercial.forvo.com/

**Comment by lucwastiaux** [comment]
what API url are you supposed to your with your API key ?

**Comment by brothamanben** [comment]
i'm using the apicorporate.forvo.com one but the corporate api url appears to have changed 

![image](https://user-images.githubusercontent.com/68020961/105936453-a4b6d480-608e-11eb-839a-306442fa853b.jpeg)

![image](https://user-images.githubusercontent.com/68020961/105936646-08d99880-608f-11eb-9b44-4fcaab5496d5.jpeg)

**Comment by lucwastiaux** [comment]
OK I can add that one.

**Comment by brothamanben** [comment]
> OK I can add that one.

thank you so much, this will save me so much time, i was adding things one by one before

**Comment by brothamanben** [comment]
![image](https://user-images.githubusercontent.com/68020961/105949875-662e1380-60a8-11eb-9f08-5a6ae4767f78.png)


Okay I tried it again and somehow it still doesn't appear to be working 


Maybe this will help?

![image](https://user-images.githubusercontent.com/68020961/105950162-e3f21f00-60a8-11eb-8010-208a4886f559.png)

**Comment by lucwastiaux** [comment]
I just released AwesomeTTS 1.30 which should allow you to select that API URL, please give it a try.

**Comment by brothamanben** [comment]
> I just released AwesomeTTS 1.30 which should allow you to select that API URL, please give it a try.

Yes thank you, I mean that I just tried it and then received this error

**Comment by brothamanben** [comment]
When trying apicorporate.forvo.com/api2/v1.1/  I receive this error 
![image](https://user-images.githubusercontent.com/68020961/105950980-51eb1600-60aa-11eb-8f32-4afa0f5ed42b.png)


When trying apicommercial.forvo.com I receive this error 
![image](https://user-images.githubusercontent.com/68020961/105951051-6deeb780-60aa-11eb-9613-5143fb1f3e4f.png)

**Comment by lucwastiaux** [comment]
which version of AwesomeTTS are you running ?

**Comment by brothamanben** [comment]
v.1.30.0 

![image](https://user-images.githubusercontent.com/68020961/105951562-36343f80-60ab-11eb-9b68-1e803696545e.png)

**Comment by lucwastiaux** [comment]
OK. In the Forvo settings, do you see the new "apicommercial.forvo.com" option ?

**Comment by brothamanben** [comment]
I see this under the "Your Account" page 
![image](https://user-images.githubusercontent.com/68020961/105951997-ddb17200-60ab-11eb-9395-3e7b976365be.png)


I also found this: 

![image](https://user-images.githubusercontent.com/68020961/105952461-9081d000-60ac-11eb-8fcd-e452f01b59dd.png)


I see this under "Demo"
URL sent to Forvo API
(Api key is hidden with XXXX)

https://apicommercial.forvo.com/action/word-pronunciations/format/json/word/%E4%BD%A0%E5%A5%BD/id_lang_speak/186/key/XXXX/
 {
	"attributes": {
		"total": 109
	},
	"items": [
		{
			"id": 4163290,
			"word": "\u4f60\u597d",
			"original": "\u4f60\u597d",
			"addtime": "2016-02-24 13:31:58",
			"hits": 2646,
			"username": "RyanJan",
			"sex": "m",
			"country": "Taiwan",
			"code": "ne",
			"langname": "Nepali",
			"pathmp3": "https:\/\/apicommercial.forvo.com\/audio\/1g3m2i261p3o1f2i3g39372d2c3o1o363h2d2q322h3o311k39221h3f1m2a3q2f2l3f272f2337331b2a1m2j2b3338312m1n2q2j231b3b353l2m3d2l391p3o3a3k_2e2g2e221i2a1o26343p2i1f2k3m2n1g1m3a2k1h2o371t1t",
			"pathogg": "https:\/\/apicommercial.forvo.com\/audio\/271l383n2p3f3b3j31222k2o3h282l2h1f1k253e3g1g1i3k1l1o2d2l1b3g1l3b3g272a2l2j263a373n3b3o21252k213q3g1m3o392j2c2q2o3b2p371b2h2e1b1i_251m261p3j1f3m3d3j2g2o3f353i392d2o331n251g3n1t1t",
			"rate": 0,
			"num_votes": 0,
			"num_positive_votes": 0
		},
		{
			"id": 4922268,
			"word": "\u4f60\u597d",
			"original": "\u4f60\u597d",
			"addtime": "2017-04-04 13:19:04",
			"hits": 631,
			"username": "mxdcs20275",
			"sex": "m",
			"country": "China",
			"code": "ny",
			"langname": "Chichewa",
			"pathmp3": "https:\/\/apicommercial.forvo.com\/audio\/2d352k3q2l2j2m28362d241j1l1j383j3j2q3d2p35263n2m3h1p1g372l3g2q2i2h2l3j2l2g2f2n24392j381m321f2o2i2g1i1i2o2q1b1m2f2d3i3n2f1l2e3e21_3o3427261o2a3p2h3i1o2g3n3h2l3q2c2b361j2m34211t1t",
			"pathogg": "https:\/\/apicommercial.forvo.com\/audio\/3i3i2b3p3j1p3l1m3a27243m352o21282p2c362f2c1k32363j1m1j231m39292539263k2c2d33381f2c392c3n1i2i3d21213l25272a3g3m2c323h2h3m1j2q392n_3d2i363k2a2h2i2d3g3b1p2h3m1l1l2q1h392f372j371t1t",
			"rate": 0,
			"num_votes": 0,
			"num_positive_votes": 0
		},
		{
			"id": 5795430,
			"word": "\u4f60\u597d",
			"original": "\u4f60\u597d",
			"addtime": "2018-05-13 15:19:31",
			"hits": 603,
			"username": "harveys",
			"sex": "m",
			"country": "China",
			"code": "zh",
			"langname": "Mandarin Chinese",
			"pathmp3": "https:\/\/apicommercial.forvo.com\/audio\/251o2l3g3j2a332h1o2p2a3p1h2m2m3k2k3l2k2j1h1g2b1k3g2o212q1j3k2i35291g3p2a2k2p2e2h2j3i1p393q3b2j393n2m1h3g2o1b1i2n2n363l3l2l3f292l_1l2e2n2n3d2i242526221k3e373d1h393b332d2n3o211t1t",
			"pathogg": "https:\/\/apicommercial.forvo.com\/audio\/1b1l3f3p332n3e291l32352d1j28212h252j3a332p283a2n331j312l2g1n3l1o1l1g2f3f3k2k2l28211i3623311n3m2732393o2g3a1m383a2o21332h3b2e2g2j_1k1b2h26281g3i3j2d232k3f1k3e3p2p3b3i3m1k2f211t1t",
			"rate": 0,
			"num_votes": 0,
			"num_positive_votes": 0
		},

**Comment by lucwastiaux** [comment]
Go to the Forvo settings in AwesomeTTS and look at the API URL dropdown, do you see apicommercial.forvo.com ?

**Comment by brothamanben** [comment]
> Go to the Forvo settings in AwesomeTTS and look at the API URL dropdown, do you see apicommercial.forvo.com ?

Yes I do,
![image](https://user-images.githubusercontent.com/68020961/105953224-c7a4b100-60ad-11eb-8762-e74552aa07a5.png)


But when I use it I get this error
![image](https://user-images.githubusercontent.com/68020961/105953325-f589f580-60ad-11eb-8133-5abb0d70ce95.png)

**Comment by lucwastiaux** [comment]
@brothamanben please share your API key with me: awesometts@airpost.net and i'll try to figure it out.

**Comment by brothamanben** [comment]
> @brothamanben please share your API key with me: [awesometts@airpost.net](mailto:awesometts@airpost.net) and i'll try to figure it out.

okay I'll be emailing from fooheads@gmail.com
