### ISSUE TITLE
IBM Watson, have a personal made API. Getting error 403?

### ISSUE THREAD

**Issue by yaoberh** [AwesomeTTS/awesometts-anki-addon#176]
Is this due to the fact that its only for plus members now? I don't understand.

**Comment by lucwastiaux** [comment]
No, it should work with your own API key. Can you share your API key with me? awesometts@airpost.net I can help you look into it.

**Comment by barolo** [comment]
Watson been down for some zones recently it's always best to check the dashboard first for announcements.
It's working for me with the zone set to Frankfurt [closest to me]

**Comment by lucwastiaux** [comment]
Discussed privately and the issue was resolved.
