### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by michaelcward1996** [AwesomeTTS/awesometts-anki-addon#183]
Newest update comes up with an error

[Errno 2] No such file or directory: 'C:\\Users\\micha\\AppData\\Roaming\\Anki2\\addons21\\1436550454\\awesometts\\.cache\\naverclovapremium-013558c0-42210cff-30a7800c-87300d87-eb43a275.mp3'

**Comment by lucwastiaux** [comment]
Can you post the full stack trace?

**Comment by michaelcward1996** [comment]
I unfortunately can't. One because I don't know how, and two, because even though nothing I did fixed the problem yesterday, today the error has up and disappeared 🤪. Have a good weekend :)

**Comment by lucwastiaux** [comment]
Understood, feel free to reopen if this happens again.
