### ISSUE TITLE
error on new version ANKI with proxy

### ISSUE THREAD

**Issue by hhelibeb** [AwesomeTTS/awesometts-anki-addon#184]
I‘m in China and have to use google cloud tts with **proxy** (Clash). And Awesome TTS was working fine with proxy on **ANKI 2.1.35**.

But now I install the new version ANKI **2.1.40**. When run the Awesome TTS to generate voice using google tts , it hints:

Cannot peview the input phrase with these stings.
HTTPSConnectionPool(host= 'exttospeech.googleapis.com', port=443)
Max retries exceeded with url: /v1 /text:synthesize?
key=. mykey (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation ofprotocol ( ssl.c:1124)))

![图片](https://user-images.githubusercontent.com/16676760/108437114-a176c900-7287-11eb-87c8-dee5388e2142.png)

When I downgrade ANKI to 2.1.35, it works again.

Steps to reproduce this error.

Set a system proxy (for me it is a clash proxy)
Open Anki Browser
Select a note
Click Awesome TTS > Add Audio to Selected
Fill a word in "Preview" and click the Preview

Environment:
Anki Version ⁨2.1.40
Awesome TTS version: v1.13.0/v1.34.0
OS: Windows 10 
Sound I am trying to use: Google Cloud TTS

**Comment by lucwastiaux** [comment]
Can you provide a bit more detail on when this happens, does it happen all the time , or only after a number of cards have been generated ?

**Comment by hhelibeb** [comment]
> 
> 
> Can you provide a bit more detail on when this happens, does it happen all the time , or only after a number of cards have been generated ?

Yes, it happens all the time. I tried to reinstall ANKI/Clash/Windows, and the issue was still reproduced.

**Comment by lucwastiaux** [comment]
Have you tried with a different VPN ?

**Comment by brownbat** [comment]
Sounds similar to #153. Was hoping that was just going to be me.

**Comment by lucwastiaux** [comment]
@brownbat are you in China and using a VPN ?

**Comment by brownbat** [comment]
I am not in China, but that other issue occurred when I was using a VPN, so at the time I worried Google had undisclosed abuse prevention measures that were preventing use by VPNs and proxies worldwide.

My workaround was to simply stop using a VPN, but I can see how that wouldn't work in some countries.

**Comment by lucwastiaux** [comment]
Unfortunately it's very difficult for me to troubleshoot VPN issues, in some cases I may be unable to help. One thing you could try doing is to sign up for the trial of AwesomeTTS Plus and see whether those issues are still happening : https://languagetools.anki.study/awesometts-plus
