### ISSUE TITLE
Audio disappears (?) when adding through keyboard shortcut

### ISSUE THREAD

**Issue by c-ehrlich** [AwesomeTTS/awesometts-anki-addon#185]
Recently I've that an issue where if I create TTS with CMD+T a reference to an audio file (ie filename in brackets) will appear in the Sentence Audio field in the browser, but when I preview the card the audio isn't there and switching to a different card and then back to the card I added TTS to makes the Sentence Audio field in the browser become empty again as well. 

On the other hand putting the cursor in the Sentence Audio field, clicking the AwesomeTTS logo in the browser and adding the audio that way works all the time.

This is not new to the current version of AwesomeTTS, I've had the bug for at least a few weeks now.

**Comment by lucwastiaux** [comment]
Could you show me a screen recording of the behavior which is problematic ?

**Comment by c-ehrlich** [comment]
Here's a screen recording. Apologies for the sound quality. I also figured out how to consistently reproduce this issue: when the cursor is in the field that the AwesomeTTS audio will be inserted to, the bug happens. When the cursor is in any other field, it does not.

[2021-03-29 21-44-42.mkv.zip](https://github.com/AwesomeTTS/awesometts-anki-addon/files/6224171/2021-03-29.21-44-42.mkv.zip)

**Comment by c-ehrlich** [comment]
I'm not sure when exactly (I just started avoiding to put the cursor in that field), but it seems to have been fixed. Closing.
