### ISSUE TITLE
AwesomeTTS make Anki remain in background processes

### ISSUE THREAD

**Issue by davyzhu** [AwesomeTTS/awesometts-anki-addon#190]
To reproduce the problem:
0. Disable other Add-ons, disable win 10 defender anti-virus
1. Create a card and open AwesomeTTS, record a mp3 file
2. Close Anki by Click up-right corner cross.
Anki will remain in background processes.
3. Reopen Anki, it will show up but have no response, and setting icon(gear) don’t display properly

Environment: 
Win 10
Anki 2.1.42(or 2.1.41)
AwesomeTTS 1.34.0

![tts3](https://user-images.githubusercontent.com/149704/110714835-19a92c80-823f-11eb-9860-4553c431ae3e.png)
![tts1](https://user-images.githubusercontent.com/149704/110714849-2037a400-823f-11eb-8335-b859a78061a3.png)
![tts2](https://user-images.githubusercontent.com/149704/110714858-2299fe00-823f-11eb-9965-83083a9405ae.png)
![tts4](https://user-images.githubusercontent.com/149704/110714875-288fdf00-823f-11eb-8448-362f761f87ac.png)
![tts5](https://user-images.githubusercontent.com/149704/110714892-2ded2980-823f-11eb-8d0c-c48f7eace015.png)
![tts6](https://user-images.githubusercontent.com/149704/110714896-304f8380-823f-11eb-95e9-f2fbdce2de4f.png)

**Comment by davyzhu** [comment]
I have simplify it by suggestion from dae:
0. Open Anki, Enable AwesomeTTS
1. Click “add”, Click AwesomeTTS Icon, Don’t have to create mp3, close AwesomeTTS
2. Disable all add-ons, Close Anki
3. Find mpv in Task Manager and terminate it
4. Reopen Anki, problem still exist

**Comment by lucwastiaux** [comment]
I'm having trouble reproducing these steps, I can generate audio on AwesomeTTS and it doesn't prevent Anki from closing. Is that the first symptom - Anki not closing ?

**Comment by davyzhu** [comment]
Anki is running after I close it by click right corner cross.
And, yes, this happen regardless of which service I use. Actually, I just open AwesomeTTS and close it, don’t have to create audio file.

Before I open AwesomeTTS, Anki’s CPU usage is about 1%. After I open AwesomeTTS, Anki’s CPU usage increase to 16%. I have a 6 logical core CPU, so I guess AwesomeTTS run into some kind of infinite loop and eat up one logical core. Then I close Anki, and after a few minutes, it’s still running, CPU usage is about 16%, see screenshot.

![image](https://user-images.githubusercontent.com/149704/111088033-19bb6c00-8560-11eb-8a9b-77baa89b4b73.png)

**Comment by lucwastiaux** [comment]
I'm able to reproduce this now, a mandatory step is to start up AwesomeTTS from the button in the editor.

**Comment by lucwastiaux** [comment]
@davyzhu please get in touch with me awesometts@airpost.net , i want to send you a reward for reporting this bug.
