### ISSUE TITLE
Anki not responding

### ISSUE THREAD

**Issue by qbroxin** [AwesomeTTS/awesometts-anki-addon#192]
Windows 10 Pro
Anki version 2.1.42
AwesomeTTS v1.35.0

Every time I try to add audio to a card, Anki becomes "Not responding" and I have to kill it. I have already tried to downgrade to Anki 2.1.35 and 2.1.40, but it had not fixed the issue. Previously I had not any issues with the AwesomeTTS.

[https://ibb.co/60pRz5X](url)

**Comment by lucwastiaux** [comment]
Anki 2.1.42 and AwesomeTTS v1.35 should work. Can you confirm you've restarted Anki after upgrading AwesomeTTS?

**Comment by qbroxin** [comment]
I've restarted Anki and the computer multiple times but it doesn't seem to fix the issue.

**Comment by lucwastiaux** [comment]
how do you add audio ? Using the batch generator (from the browser) or from the editor ?

**Comment by qbroxin** [comment]
Nothing fancy, just Browse -> Select card -> AwesomeTTS -> Add audio to Selected... -> Anki not responsing
![2021-03-15 14_54_30-Window](https://user-images.githubusercontent.com/80670638/111157037-12678300-859f-11eb-83fe-05cd28bafcb0.png)

Ctrl + T does nothing
Remove Audio from Selected... removes audio from cards

**Comment by qbroxin** [comment]
I uninstalled Avast, and Anki + AwesomeTTS work fine now.

**Comment by lucwastiaux** [comment]
thank you for the update @qbroxin
