### ISSUE TITLE
Text to Speak no longer auto-populates

### ISSUE THREAD

**Issue by SigmaX** [AwesomeTTS/awesometts-anki-addon#193]
Behavior changed in v1.35 so that when the "Record and Insert an Audio Clip w/ AwesomeTTS" button is pressed, the text to speak is now populated from the clipboard.

It used to be populated from the Anki field the cursor was in when the button is pressed.

**Steps to Reproduce**

Place text like "Hello world" in a field while editing or adding a card.
Press the AwesomeTTS button while the field still has focus

![image](https://user-images.githubusercontent.com/313154/111322407-472b1700-863f-11eb-9b56-df638f862c11.png)

**Expected Behavior**

The "preview and record" field will be auto-populated with text from my card, "Hello world", so I don't have to type it manually.

**Observed Behavior**

The "preview and record" field is populated with whatever I last "copied" to the clipboard from within Anki.

It doesn't seem to populate from text I copied to the clipboard from other apps.  I observe this behavior on both Linux and macOS.

In order to use AwesomeTTS, I now must manually select and hit "Cntrl + C" on everything I want to send to TTS.  This triples the number of clicks and keystrokes to my workflow.

![image](https://user-images.githubusercontent.com/313154/111322553-6e81e400-863f-11eb-8382-4cb6c42c73e3.png)

***

This behavior is useless to me.  If I want to copy-and-paste, I'll hit "Cntrl + V."

**Comment by lucwastiaux** [comment]
I've had to disable this feature temporarily because AwesomeTTS was previously doing something unorthodox in Javascript which resulted in Anki 2.1.42 freezing. I'm looking into how to restore this functionality, should be able to do so very quickly. I'll update you ASAP.

**Comment by lucwastiaux** [comment]
@SigmaX the issue has been fixed in v1.36. Please contact me awesometts@airpost.net to claim your reward.
