### ISSUE TITLE
Is there a way to disable the fallback voices?

### ISSUE THREAD

**Issue by shubniguroth** [AwesomeTTS/awesometts-anki-addon#197]
Occasionally when Google Wavenet takes too long to return a file, AwesomeTTS reverts to my onboard local US_EN voice from MacOS. I have to confess that I f#*&ing hate this. It sounds so robotic and out of place. I know some people must really love this feature, but I hate it.

And I would like to make it never ever happen if possible.

Is that possible? Is there some way to make AwesomeTTS automatically wait and sleep and re-query instead of falling back? Or to make it forget that it's fallen back and uncache specifically those files?

Thanks for any help you can provide,
Shub

**Comment by lucwastiaux** [comment]
Just checking, is batch generation an option for you ? 
How often does google fail to generate audio ? are you using a free key ?

**Comment by shubniguroth** [comment]
-So I cannot use batch generation, because all of my corpora (literally every single card) has at least 1, usually 2+, cloze deletions. I could go through the trouble of making multiple fields for each cloze, but it truly is not worth it.

-It fails maybe 1 out of every 20 cards. But I'm doing 850+ cards a day, so it becomes noticeable!

-I am using my own private API key for my Google Cloud account that I also use for a bunch of other API uses.

Happy to provide any/all other info as necessary!!

**Comment by shubniguroth** [comment]
Interestingly, btw, Google Cloud does not think there are any errors/fails.  (see attached: https://i.imgur.com/GskGGhS.png)

It does not list a single one. So my guess is that GCP Wavenet is just too slow occasionally and so AwesomeTTS interprets that as a fail, even if Google actually returns the file like 20 seconds later or w/e. 

Also I have it set to sleep every 10 operations for 30 seconds in the AwesomeTTS settings, which I believe is the default.

**Comment by lucwastiaux** [comment]
Would you be able to try the steps here https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Debug-Logging and attempt to trigger the problematic case, so that I can understand what is happening ?

**Comment by shubniguroth** [comment]
> Would you be able to try the steps here https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Debug-Logging and attempt to trigger the problematic case, so that I can understand what is happening ?


I use MacOS, so is the procedure the same or...?

**Comment by lucwastiaux** [comment]
I just added some instructions on that page, could you try it ? https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Debug-Logging

**Comment by shubniguroth** [comment]
This is actually fixed now at least after v 1.38. No longer happening to me
