### ISSUE TITLE
Single note edit AwesomeTTS

### ISSUE THREAD

**Issue by Gursharn007** [AwesomeTTS/awesometts-anki-addon#199]
since the update,

It refuses to read the front note feild in single note edit. 

For example I have written Apple on my card.
When I press Ctrl T in single note editor, nothing shows up in the preview field. 
This is quite annoying.

**Comment by lucwastiaux** [comment]
what's your version of Anki ?

**Comment by Gursharn007** [comment]
ok fixed my bad. Updated anki to latest version. All is good now.

**Comment by lucwastiaux** [comment]
Anki introduced a breaking change in 2.1.41 which forced us to make this change.
Is it all working for you now ? If you're satisfied please leave a review: https://ankiweb.net/shared/info/1436550454

**Comment by Gursharn007** [comment]
Yes, it is working. Will do
