### ISSUE TITLE
No audio or only one service at a time

### ISSUE THREAD

**Issue by yaoberh** [AwesomeTTS/awesometts-anki-addon#200]
This started happening with the latest update, with on-the-fly or normal audio generation. Presets or single service.
It says no service was able to generate audio.
Tried with multiple languages and all have the same problem.
Some presets which contain for example 10 different french voices randomly have 1 working voice only sometimes.
The log shows 403 errors to all providers which it couldn't connect to.

**Comment by lucwastiaux** [comment]
Were you able to use this method to write a debug log file ? https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Debug-Logging

**Comment by yaoberh** [comment]
Yes, this is the log I found in my anki folder:
[awesometts.log](https://github.com/AwesomeTTS/awesometts-anki-addon/files/6251682/awesometts.log)

**Comment by lucwastiaux** [comment]
this log shows you're only making one request to Naver Papago, did that one work ?

**Comment by yaoberh** [comment]
As a matter of fact I just tested that one with a phrase and it's working. All other services seem to hang after pressing the preview button and then the preview button appears again but no sound is played.

**Comment by yaoberh** [comment]
Getting this error with azure and amazon:
Cannot preview the input phrase with these settings.

Status code: 429 (b'{"error": "Exceeded User lifetime quota"}\n')

**Comment by lucwastiaux** [comment]
As discussed over email, this is because you've used up all of your trial limit.

**Comment by yaoberh** [comment]
You didn't answer my latest email, in which I explain that this is impossible if you gave me 100K requests and I've only probably used anki thrice last week. I didn't even use batch generate because I only use presets for on-the-fly. Even if I had 10K I must have maximum donde 2 or 3K at the most.

**Comment by windweb** [comment]
> Cannot preview the input phrase with these settings.
> 
> Status code: 429 (b'{"error": "Exceeded User lifetime quota)"}\n')


**I am a user from Russia. Perhaps this error is due to the sanctions.** 

A cry from the soul:
_Now we have been cut off from all services. I fight for peace in my country, but I only get blows to the head from the security forces in Putin's service and fines. Now getting stabbed in the back by companies overseas. Fine. Thank the world for this fascism towards Russians, which is comparable to the fascism towards Jews in the 1930s and 1940s. It cannot lead to anything good._

**Comment by luc-languagetools** [comment]
@windweb please contact me by email awesometts@airpost.net
