### ISSUE TITLE
Enhancement: Speak arbitrary text

### ISSUE THREAD

**Issue by NSBum** [AwesomeTTS/awesometts-anki-addon#201]
The current tag format requires that the field name be specified. However I have several card types where I use JS to make alterations to the field before display. It would be ideal if AwesomeTTS would permit speech of arbitrary text inserted by JS in the card template. Is this possible/desirable?

**Comment by lucwastiaux** [comment]
what kind of alterations ? AwesomeTTS supports regexp replacements, would this help you ?

**Comment by NSBum** [comment]
Yes, in other circumstances I've used the regex text preprocessor in AwesomeTTS to do this, but the rules are applied at an overall level that's not specific to a given card type.

**Comment by lucwastiaux** [comment]
this sounds like something I could add in awesometts2. But to help me, can you give me an example of a card-type specific processing that you want to do ?

**Comment by NSBum** [comment]
Sure, a situation where the desired speech output is the lemma of a word not the displayed word itself. That's the sort of transformation I had in mind where the regex processor in AwesomeTTS wouldn't be enough, where in 99% of other cases its perfectly useful. If it introduces undesired complexity in the add-on, it's not a show-stopper for me.

**Comment by lucwastiaux** [comment]
Why do you not pre-generate the particular text you want to have pronounced ? That would be much easier to do in the Anki + AwesomeTTS framework. Doing this in Javascript seems to be more complicated.
