### ISSUE TITLE
AwesomeTTS gets error

### ISSUE THREAD

**Issue by Albert090909** [AwesomeTTS/awesometts-anki-addon#204]
Since the latest update from AwesomeTTS I get the following Errow if I try to use it:

Fehler
Es ist ein Fehler aufgetreten. Bitte starten Sie Anki neu und halten Sie während des Startvorgangs die Umschalttaste gedrückt, damit Anki die installierten Erweiterungen temporär deaktiviert.
Wenn das Problem nur auftritt, wenn die Erweiterungen aktiviert sind, dann benutzen Sie bitte den Menueintrag Extras > Erweiterungen um die problembehaftete Erweiterung durch selektives Deaktivieren herauszufinden.
Wenn Sie die entsprechende Erweiterung herausgefunden haben, dann bitten wir, dass Sie sich mit einem entsprechenden Problembericht an die Support-Seite für Erweiterungen wenden, damit der Fehler behoben werden kann.
Debuginformationen:
Anki 2.1.43 (0fbae6bc) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-04-30 06:48:15

Caught exception:
Traceback (most recent call last):
File “aqt\webview.py”, line 36, in cmd
File “aqt\webview.py”, line 135, in _onCmd
File “aqt\webview.py”, line 580, in _onBridgeCmd
File “aqt\editor.py”, line 466, in onBridgeCmd
File “aqt\editor.py”, line 796, in onRecSound
File “aqt\sound.py”, line 799, in record_audio
File “aqt\sound.py”, line 715, in init
File “aqt\sound.py”, line 756, in _start_recording
File “aqt\sound.py”, line 567, in start
AttributeError: ‘NoneType’ object has no attribute ‘readyRead’

Regards
Albert

**Comment by lucwastiaux** [comment]
Hi, what triggers this error ? from the stack trace, it's not very clear if AwesomeTTS is involved.

**Comment by Albert090909** [comment]
Hi, sorry if it was unclear.
I fill up the template fields, cursor was behind the word and I press the TTS Button.
![grafik](https://user-images.githubusercontent.com/83457013/116710395-00686500-a9d2-11eb-8211-4046e1c04fdc.png)
After pressing the TTS Button i get this error.
Regards
Albert

**Comment by Albert090909** [comment]
I did an update of this plug in yesterday and it seams since this it doesn't works.

**Comment by lucwastiaux** [comment]
This button is not the TTS button, it's the record button, unless i'm misunderstanding something.

**Comment by Albert090909** [comment]
Please excuse the misunderstanding.
This is what happens when you do too many things at once.
Next time I'll drink a coffee first :), sorry.
Thank you for your support, it fkt.
Many greetings
Albert
