### ISSUE TITLE
Support SSML Tags for Microsoft Azure

### ISSUE THREAD

**Issue by hieuvijjo** [AwesomeTTS/awesometts-anki-addon#205]
Could you please support SSML Tags for Microsoft Azure voice?
Tags such as `<break time="1000ms"/>` seem to work with Google Cloud TTS but they don't with Microsoft Azure.

**Comment by lucwastiaux** [comment]
yes I can look into this

**Comment by hieuvijjo** [comment]
Awesome!!! Thank you very much!

**Comment by lucwastiaux** [comment]
this is still coming, but haven't had much time lately, will keep you updated.

**Comment by lucwastiaux** [comment]
SSML support should be available in AwesomeTTS 1.45, please give it a try.

**Comment by hieuvijjo** [comment]
Awesome!!! It works like a charm :D Thank you very much! May I send you some support? Do you have a ko-fi account?

Best regards,

--
Hieu Cao
Email: ***@***.***

**Comment by lucwastiaux** [comment]
If you feel happy with the support please write a review here https://ankiweb.net/shared/info/1436550454
