### ISSUE TITLE
Naver Papago

### ISSUE THREAD

**Issue by Pvb04** [AwesomeTTS/awesometts-anki-addon#207]
May - 24 - 2021
Naver Papago option is returning error "No response for web request"

Was working as of Thursday, May - 20

**Comment by darafsa** [comment]
I'm pretty sure it worked untill May - 23. Broke for me as well yesterday

**Comment by lucwastiaux** [comment]
thanks for notifying. this happens regularly, let me try to look into it.

**Comment by lucwastiaux** [comment]
@Pvb04 @darafsa Naver Papago is fixed in AwesomeTTS 1.41. If you feel satisfied by my fix, please leave a review on https://ankiweb.net/shared/info/1436550454

**Comment by darafsa** [comment]
thank you so much also for your quick reaction!

**Comment by darafsa** [comment]
Of course, I did already :D

**Comment by WilsonNet** [comment]
I'm getting a JSON response asking that login is required.

![image](https://user-images.githubusercontent.com/25280488/120085620-31f74d80-c0b0-11eb-97b5-e302de590a46.png)

**Comment by lucwastiaux** [comment]
@WilsonNet please try again with version 1.42

**Comment by WilsonNet** [comment]
It's working, thanks, gonna leave that review.
