### ISSUE TITLE
Plugin shortcode does not let the anki know if the added card is a duplicate or not

### ISSUE THREAD

**Issue by ulin-evgeny** [AwesomeTTS/awesometts-anki-addon#208]
I am adding a new card to the deck. I don’t write the shortcode to the question (I don’t have a pronunciation yet - the file has not been downloaded). A card that is already in the deck has a shortcode. This prevents anki from giving me an error that such a card already exists.

Before adding a new card, I have to open the deck and look for the word that I want to add to the question. I do not like this.

What can I do? Except for the transfer shortcode to the answer or example (I don't like these options, since I will only hear the pronunciation after I click on the "Show Answer" button)?

**Comment by lucwastiaux** [comment]
I'm not completely clear how this problem is specific to awesomeTTS, what do you mean by shortcode ? Is there any way you could record a screen capture to illustrate this issue ?

**Comment by ulin-evgeny** [comment]
Shortcode is for example: 
`[sound:sapi5com-7aa8a590-d6ccd225-59503436-3845558f-38455822.mp3]`
If I add this to the question of the card in order to hear the pronunciation when showing the card, then when I add a new card to the deck with the same question, but without the shortcode, the anki will not give me an error that such a card already exists. I am attaching screenshots.

<img width="1062" alt="Anki question 1" src="https://user-images.githubusercontent.com/13357847/120930725-25e63e00-c6f7-11eb-9e80-8d164756a60e.png">
<img width="1007" alt="Anki question 2" src="https://user-images.githubusercontent.com/13357847/120930729-2b438880-c6f7-11eb-9c79-e3f3e26ee4ab.png">

**Comment by ulin-evgeny** [comment]
I solved my problem. A new field had to be added. I didn’t know that there was such an opportunity in Anki.
Video that helped me: https://www.youtube.com/watch?v=KvboCY_ookE .
