### ISSUE TITLE
The new Version does not work for me

### ISSUE THREAD

**Issue by Trichosanthes** [AwesomeTTS/awesometts-anki-addon#211]
It is a big desaster. I was sooooo happy with the former version. I used Oddcast TTS for my Japanese Cards - it was great! No I can't get any TTS working. How can I go back to the former Version. Please Help!!!

**Comment by lucwastiaux** [comment]
Hi @Trichosanthes , could you contact me by email: awesometts@airpost.net ? I want to help you fix the issue.

**Comment by Trichosanthes** [comment]
Hello LucW,

I'm sorry, I freaked out a little this morning. In meanwhile I was able to restore v1.32.0 and it works fine for me.
If there are no more problems, I will not change anything. I am very happy with awesometts-anki-addon, so thank you very much!

Trichosanthes

**Comment by lucwastiaux** [comment]
If everything works for you, could you change your negative review here ? https://ankiweb.net/shared/info/1436550454
