### ISSUE TITLE
No audio at all.

### ISSUE THREAD

**Issue by yaoberh** [AwesomeTTS/awesometts-anki-addon#213]
I'm having a problem which is that I have no audio at all with on-the-fly generation.
It isn't language specific because I tried at least 10 and they all just don't play any sound.
The preview button does not cause any errors and I don't get any either while reviewing.
Log shows 429 and 430 errors.

**Comment by lucwastiaux** [comment]
Please use debug logging and share your log https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Debug-Logging
