### ISSUE TITLE
Microsoft Azure "API Key Not Valid"

### ISSUE THREAD

**Issue by Boohooyoohoo** [AwesomeTTS/awesometts-anki-addon#217]
Hi,

When I verify my API key for Microsoft Azure TTS API key AwesomeTTS does not recognise it, I get the error "API Key Not Valid". Can someone help me to fix this problem? Thanks!

**Comment by lucwastiaux** [comment]
Can you describe what you're trying to do exactly ?

**Comment by Boohooyoohoo** [comment]
Thanks so much for your reply, I am trying to set up AwesomeTTS with a Microsoft Azure key.

I have created a Microsoft Azure account and set up my payment details. I created a Resource Group in East US, and created a "Speech" resource within that group. The Speech resource is set up to be pay for use and pricing tier free. It now shows as a Cognitive Service, and I have two keys. However, when I paste either key in Anki under Tools > AwesomeTTS > Advanced > AwesomeTTS Plus the key does not verify. Probably I am doing something wrong, but cannot figure out what it is.

<img width="1036" alt="Screenshot 2021-07-18 at 11 46 32" src="https://user-images.githubusercontent.com/87549182/126062704-45f3eb71-2156-4b71-bc72-5d11ce3a6081.png">

<img width="613" alt="Screenshot 2021-07-18 at 11 47 11" src="https://user-images.githubusercontent.com/87549182/126062721-1bc45ba4-906b-42f5-8180-4b4b6cc38e57.png">

**Comment by lucwastiaux** [comment]
ah I see. You created your own Azure key, just enter this into the services dialog (click Manage Presets in the screenshot above, then select Microsoft Azure). The AwesomeTTS Plus offering gives you access to all services, not just Azure. You can read about it here: https://languagetools.anki.study/awesometts-plus . You can sign up for a trial if you're interested.

separately I like your window manager appearance, I assume you're running linux, what desktop environment ?

**Comment by Boohooyoohoo** [comment]
> ah I see. You created your own Azure key, just enter this into the services dialog (click Manage Presets in the screenshot above, then select Microsoft Azure). The AwesomeTTS Plus offering gives you access to all services, not just Azure. You can read about it here: https://languagetools.anki.study/awesometts-plus . You can sign up for a trial if you're interested.
> 
> separately I like your window manager appearance, I assume you're running linux, what desktop environment ?

Hey man thanks so much for helping, it now works beautifully. I believe you are the developer of the app am I right? You are doing great work, this app makes studying much easier and it is awesome that it exists. Also great that you take the time to help people on this forum. I will recommend your AwesomeTTS plus service to my fellow students. 

I am not running Linux,, just the latest version of MacOS. Thanks again!

**Comment by lucwastiaux** [comment]
You're welcome, thank you so much for your compliments ! If you feel satisfied with my service, please leave a review on https://ankiweb.net/shared/info/1436550454
