### ISSUE TITLE
After adding a card template using on-the-fly tts audio one banner shows up.

### ISSUE THREAD

**Issue by JimHalen** [AwesomeTTS/awesometts-anki-addon#222]
I added a card template following the instructions provide on the on-the-fly tts wiki, but after adding it one banner shows up and I can't find a way to make it disappear again. Note that the on-the-fly tts is working fine but this banner is very annoying. Can someone help me?

Obs: you can see the annoying banner here: https://imgur.com/a/aDErwK8

**Comment by lucwastiaux** [comment]
AwesomeTTS menu -> advanced, uncheck "show AwesomeTTS widget on Deck Browser".

**Comment by JimHalen** [comment]
Exactly, thank you!
