### ISSUE TITLE
AwesomeTTS reads more than it is wished

### ISSUE THREAD

**Issue by Golddouble** [AwesomeTTS/awesometts-anki-addon#229]
I use AwesomeTTS in AkiDroid.

I have a card that looks like this:
Front:
```
Rechtschreibung ?<br><br>
<div style='font-family: Arial; font-size: 0px;'>{{Vorderseite}}</div>
{{type:Vorderseite}}
```
{{type:Vorderseite}} is needed so that a field appears, so that the learner can type in this field the solution of the Anki question. AnkiDroid does the control the spelling in this field.

What happens:
When the card appears AwesomeTTS reads "Rechtschreibung ?  {{Vorderseite}}  type:Vorderseite"

What I want to have:
My wish would be, that in this card only "{{Vorderseite}}" is read by AwesomeTTS.

Ist there something I can do? Thank you.

**Comment by Golddouble** [comment]
Here is the solution:
Just add:
```
    <tts service="android" voice="en_GB">
       ...
    </tts>
```
So that the full example now looks like this:
```
Rechtschreibung ?<br><br>
<tts service="android" voice="en_GB">
<div style='font-family: Arial; font-size: 0px;'>{{Vorderseite}}</div>
</tts>
{{type:Vorderseite}}
```

**Comment by lucwastiaux** [comment]
Are you reviewing exclusively on AnkiDroid ? Given you use on the fly TTS, AwesomeTTS has no role there. I wanted to point this out so that we can find a solution for you.
