### ISSUE TITLE
Voice for Collins Dictionary doesn't work anymore

### ISSUE THREAD

**Issue by Iey4iej3** [AwesomeTTS/awesometts-anki-addon#23]
Hello,
It seems to me that AwesomeTTS doesn't generate voice any more by passing the French voice to Collins.
I tried many words, including "bonjour" and "ciseler", which are available online:
https://www.collinsdictionary.com/dictionary/french-english/bonjour
https://www.collinsdictionary.com/dictionary/french-english/ciseler
Thanks for verification and fix.

**Comment by lucwastiaux** [comment]
Collins french TTS works, i've added an automated test for it.
