### ISSUE TITLE
AnkiDroid speech quality on different smartphones

### ISSUE THREAD

**Issue by Golddouble** [AwesomeTTS/awesometts-anki-addon#230]
In AnkiDroid 2.15.6 (Android) on my Nokia 1 phone (cheap Entry-level model with android 10 go) I have in settings->Advanced checked the function "Text to speech".

This works well. French speech is clear, not to fast and sounds natural.

As I am a private tutor, I have made the collection available to my student via sync. I don't know what kind of smartphone he has, but I'm guessing a mid-range device.

But I am very confused, that French speech sounds very different on his phone. Too fast, less clear and less natural?

What can be the reason for this?

It does not look like there are any "AwesomeTTS" options or settings in AnkiDroid. We can just check or uncheck the function "Text to speech". Or did I miss anything?
Further my expectation was, that on my Nokia 1 phone the speech would be worse than on the pupils middle class phone. But it is just the other way round. Why?

On both phones there are no "self-made audio-files" it is just the same collection.

Would appreciate some input. Thank you.

**Comment by Golddouble** [comment]
Please note: AnkiDroid uses TTS from Android OS. It is not integrated in AnkiDroid.

**Comment by lucwastiaux** [comment]
@Golddouble did you generate audio in batch the way it's described here ? https://languagetools.anki.study/tutorials/awesometts-batch-generation

**Comment by Golddouble** [comment]
This answer does not suite to my question.

Nevertheless: This is great information for me, because I also use the desktop version of Anki. And until now, I was not able to get speech there with the addon "AwesomeTTS".

But now, thanks to your link, I was able to generate speech for Anki Desktop.

Thank you very much.

**Comment by lucwastiaux** [comment]
If you want reliable audio quality on AnkiDroid, the only way to achieve that is to batch generate audio on desktop and then sync it to your ankiweb account. That way, you'll get the exact same sounds while reviewing on mobile. Does this solve your problem ?

**Comment by Golddouble** [comment]
> Does this solve your problem ?

Thank you. Yes, this would would be a workaround to solve the issue.

> If you want reliable audio quality on AnkiDroid, the only way to achieve that is to batch generate audio on desktop and then sync it to your ankiweb account.

I guess "the only way" is not correct here, because on my own phone I have reliable audio quality.
I was not able to test the following second way, because my pupil is in holiday. But I have found out, how my phone generates the sounds on AnkiDroid:

In my Android OS the following App. is installed:
https://play.google.com/store/apps/details?id=com.google.android.tts

My guess is, that the pupil has another service installed and that this would be the reason for the different speech quality. So I will suggest him to install this better service and activate it in Android settings.
