### ISSUE TITLE
Could you add the FPT.AI AceSound voices to AwesomeTTS?

### ISSUE THREAD

**Issue by BigUncleKerch** [AwesomeTTS/awesometts-anki-addon#234]
Is it possible to add the 5 **AceSound** voices (which are similar in voice quality to the Cloud/Azure TTS quality) which can be previewed on the FPT.AI TTS website: https://fpt.ai/tts to AwesomeTTS?

I bought a AwesomeTTS subscription to access the FPT.AI voices but was disappointed to realise that it didn't have the AceSound Voices. Currently AwesomeTTS only supports the lower quality voices which are not AceSound.

**Comment by lucwastiaux** [comment]
Yes i can look into it, give me a day or two.

**Comment by BigUncleKerch** [comment]
> Yes i can look into it, give me a day or two.

Awesome, thanks so much Luc!

**Comment by lucwastiaux** [comment]
Done, available in AwesomeTTS 1.52. If you feel satisfied with this change, please leave a review here https://ankiweb.net/shared/info/1436550454

**Comment by BigUncleKerch** [comment]
> Done, available in AwesomeTTS 1.52. If you feel satisfied with this change, please leave a review here https://ankiweb.net/shared/info/1436550454

wow thanks so much! just left a review, I really appreciate it!

**Comment by lucwastiaux** [comment]
Cool ! Reminder that you can also try Language Tools which has support for translation (https://languagetools.anki.study/language-tools)
