### ISSUE TITLE
FPT.AI and "Cannot preview/record the input phrase with these settings."

### ISSUE THREAD

**Issue by pan-asian-wok** [AwesomeTTS/awesometts-anki-addon#235]
When I try to use AwesomeTTS with FPT.AI, I get the following messages:

For previewing, I received "Cannot preview the input phrase with these settings. Value for header {voice: {'voice_id': 'minhquangace'}} must be of type str or bytes, not <class 'dict'>"

![Preview FPTAI](https://user-images.githubusercontent.com/45274474/139638700-21594b58-f36d-479a-b829-02a6f38f29a2.JPG)

For recording, I received "Cannot record the input phrase with these settings. Value for header {voice: {'voice_id': 'minhquangace'}} must be of type str or bytes, not <class 'dict'>"

![Record FPTAI](https://user-images.githubusercontent.com/45274474/139638707-7ea8bc2a-8ccc-4ef5-a284-237db431ca63.JPG)

I have my own FPT.AI API key and I have confirmed that it's working on their website. I also used the same key a while ago before I took a hiatus from Anki and they were working at the time as well. This has affected all the voices that are available. Hopefully, it is an easy fix. If it's on my end, can you please let me know how to fix this error message? Thank you for all you do!

**Comment by lucwastiaux** [comment]
please note this should be fixed in AwesomeTTS 1.54, if you feel satisfied please leave a review here https://ankiweb.net/shared/info/1436550454
