### ISSUE TITLE
[Request] src folder

### ISSUE THREAD

**Issue by m1karii** [AwesomeTTS/awesometts-anki-addon#242]
Hi, could you please create `src` folder in `awesometts-anki-addon` repo and move all addon stuff like `awesometts` folder, `user_files` folder and `__init__.py` into it? By addon stuff i mean what's actually in the addon folder when i install it on my PC.

**Comment by lucwastiaux** [comment]
Can you give me some more background on what you're trying to accomplish ?

**Comment by m1karii** [comment]
Hi!
I want to clone the repo and then copy the addon stuff into the anki's addons folder as part of installation script. i understand that its possible to just clone whole repo and use that, however i'd like to use just the addon stuff. 

alternative i thought of would be inserting addon code into anki using API, however i am unaware of anki having such API

**Comment by m1karii** [comment]
Nevermind. I've found an alternative.
