### ISSUE TITLE
Arabic (Syria), Female, Amany voice returns an error as unsupported

### ISSUE THREAD

**Issue by Sowa0** [AwesomeTTS/awesometts-anki-addon#243]
Hi Luc,

I get the following error when trying to generate speech with the 'Arabic (Syria), Female, Amany أماني (Neural), Azure' parameter.

`Status code: 400 (b'{"error": "Could not generate audio: SpeechSynthesisCancellationDetails(reason=CancellationReason.Error, error_details=\\"Connection was closed by the remote host. Error code: 1007. Error details: Unsupported voice Microsoft Server Speech Text to Speech Voice (ar-SY, AmanyNeural). USP state: 3. Received audio size: 0 bytes.\\")"}\n')`

**Comment by lucwastiaux** [comment]
Hi, I see this, let me look into it and i'll get back to you.

**Comment by lucwastiaux** [comment]
I can confirm i'm able to reproduce the issue, i'll probably have to open a support issue with Azure, are any of the other Arabic voices acceptable to you in the mean time ?

**Comment by Sowa0** [comment]
I just wanted to let you know this one does not work, I have used other voices until now (I have not tried them all, other could also be missing). You could remove it from the list until Azure fixes it.

**Comment by Sowa0** [comment]
Closing this as this has now been resolved.
