### ISSUE TITLE
Voice Quality

### ISSUE THREAD

**Issue by arlisonmao** [AwesomeTTS/awesometts-anki-addon#25]
I've been using oddcast Show male/English to add audio to my flashcards. All of a sudden the quality sounds very weak as if its being recording in a very acousitcy bathroom or something. My English male voice for oddcast Paul / James in English. Why as of late, now when i attach sounds to my English cards, the audio quality in clarity has dropped like 50%. Please help.

**Comment by ibrshv** [comment]
Oddcast is now completely broken.

**Comment by lucwastiaux** [comment]
@arlisonmao @ibrshv Oddcast should work properly now.
