### ISSUE TITLE
Support anki version 2.1.50

### ISSUE THREAD

**Issue by PQTran** [AwesomeTTS/awesometts-anki-addon#253]
I'm on archlinux and I recently updated which installed anki version 2.1.50. The addon page says it only supports up to 2.1.49. I'm wondering if we can include version 2.1.50 as well?

**Comment by luc-languagetools** [comment]
Yes it's planned, but be aware that 2.1.50 is currently in beta, it's not the latest stable release.

**Comment by PQTran** [comment]
oh i see, I just realized I had installed the git package through archlinux. I'll use the stable release instead. Thanks!

**Comment by luc-languagetools** [comment]
yes please use 2.1.49 for now.
