### ISSUE TITLE
"ș" is not pronounced

### ISSUE THREAD

**Issue by michaelglatz** [AwesomeTTS/awesometts-anki-addon#26]
Hello,

using following settings:

Service: Oddcast
Voice: Simona (female ro)

the letter "ș" is left out of audio recordings, almost as if it was not even transmitted to the service.
Using the other Romanian voice works though.  But it's not a solution, as it's not as good.

**Comment by lucwastiaux** [comment]
Can you give me a full word in romanian please? If I understand properly, there's a problem with one romanian voice on oddcast, but no the other. This is most likely a problem with Oddcast, I don't think we can fix AwesomeTTS for this.
