### ISSUE TITLE
Possibility of adding windows 11 natural voices

### ISSUE THREAD

**Issue by BEST8OY** [AwesomeTTS/awesometts-anki-addon#261]
Hello 
In windows 11 microsoft has added some natural voices.
Is it possible to add them to microsoft speech api?
![Screenshot 2022-04-24 232533](https://user-images.githubusercontent.com/70865987/164992132-836185e5-a496-44e2-9d5a-cc50dc99efdd.jpg)
These voices are incredible.

**Comment by luc-languagetools** [comment]
Are these available over SAPI ? Have you you tried using them in HyperTTS ?

**Comment by BEST8OY** [comment]
> Are these available over SAPI ? Have you you tried using them in HyperTTS ?

Not Sure.
Both Addons only have Zira and David Voices in settings.

**Comment by luc-languagetools** [comment]
I'm going to look into this and get back to you.

**Comment by lovac42** [comment]
Some of these natural voices are compatible with SAPI5, but they are not accessible to 3rd party software. You need to perform a registry hack to make them available. I can't recall the exact steps I took on win 10, they may have changed for win 11. Please **backup and ask for admin permission** first, you can do some serious damage here.

https://www.google.com/search?q=windows+11+natural+voices+registry+hack
