### ISSUE TITLE
No response for web request

### ISSUE THREAD

**Issue by shinneniks** [AwesomeTTS/awesometts-anki-addon#273]
Anki: 2.1.54
AwesomeTTS: v1.68
when i played the card once it showed "no response for web request", i tried to sync or play card again then it worked. However the following card show that error again
I use Naver Pagoda
FptAi Vietnamese

**Comment by luc-languagetools** [comment]
do you know which input causes the issue ?

**Comment by shinneniks** [comment]
No, I took my laptop to repair and then a few lines of code in the card changed and also TTS;  I don't know where the reason comes from

**Comment by luc-languagetools** [comment]
understood but we'll need more details about the issue in order to solve it.

**Comment by shinneniks** [comment]
It’s back to normal today
