### ISSUE TITLE
AttributeError: 'QFontMetrics' object has no attribute 'width'

### ISSUE THREAD

**Issue by celtiberi** [AwesomeTTS/awesometts-anki-addon#275]
Support/Anki2/addons21/awesometts/awesometts/gui/base.py", line 346, in _ui_services_presets
    save.setFixedWidth(save.fontMetrics().width(save.text()) + 20)
AttributeError: 'QFontMetrics' object has no attribute 'width'

**Comment by luc-languagetools** [comment]
should be fixed in recent versions.
