### ISSUE TITLE
Google's Neural2 voices are missing.

### ISSUE THREAD

**Issue by Apocalypse612** [AwesomeTTS/awesometts-anki-addon#280]
Please implement Google's Neural2 voices, for English specifically.

Thanks!

**Comment by Apocalypse612** [comment]
I just received a newsletter that they've been added. Very nice, and thank you (should you see this). I'll kindly close this issue myself.

**Comment by luc-languagetools** [comment]
As you saw, the voices are now available, along with "News" voices. Thanks for notifying me with this issue !
