### ISSUE TITLE
Addition of voicevox support (Japanese)

### ISSUE THREAD

**Issue by 0xspringtime** [AwesomeTTS/awesometts-anki-addon#282]
Was considering writing a new add on with awesometts as the template for creating tts using voicevox since we have a great API wrapper now 
https://github.com/tuna2134/voicevox-client
https://voicevox-client.tuna2134.jp/
but was wondering whether it would be easier to just add it as a feature here. One impediment may be the need for voicevox_engine as a dependency. Is anyone else interested in this feature? I already know demand is there in the Japanese anki community.

**Comment by luc-languagetools** [comment]
Can you describe voicevox in more detail ? is it a free TTS engine ? Is it easy to install it ?

**Comment by 0xspringtime** [comment]
Yes, voicevox is a free and open source tts engine with 20+ premade voices that seems to reproduce things like pitch accent better than the paid japanese tts models and has caught on enough to be used for vocaloids. It has a cross-platform frontend that seems simple to install and even has an AUR release, the only problem is all the documentation is in Japanese.
https://github.com/VOICEVOX
https://voicevox.hiroshiba.jp/product/amehare_hau/

**Comment by luc-languagetools** [comment]
Is your proficiency in Japanese sufficient to navigate through the documentation ?

**Comment by 0xspringtime** [comment]
Probably not alone, but I haven't determined the extent to which that'd be necessary since tuna's wrapper documentation seems sufficient for integration and is in English. The problem I could see with integrating it here is that it's still reliant on the voicevox_engine as a dependency and I know that becomes cumbersome with anki since new modules have to be bundled in. So, unless some devs more familiar than I with the codebase think it's a good idea I don't want to overpush a feature specifically for the Japanese learning niche onto an established product if it could be hard to maintain.

**Comment by luc-languagetools** [comment]
OK and how does the voice quality compare to neural voices such as azure, google ?

**Comment by 0xspringtime** [comment]
imo much less robotic with more variety, along with the more accurate pitch accent mentioned before

**Comment by 0xspringtime** [comment]
I was able to implement this feature using a different add-on, detailing it here https://github.com/0xspringtime/voicevox-anki
so I'm going to close this as completed.
