### ISSUE TITLE
Microsoft Speech APl cannot find LAME to transcode audio. It may not be installed.

### ISSUE THREAD

**Issue by Benjamin-Watson0** [AwesomeTTS/awesometts-anki-addon#284]
What shall I do? I tried, but it didn't work. Ask for help.
This is the result of both "Microsoft Speech APl".
I found him.
![image](https://user-images.githubusercontent.com/112467275/216804277-8ff0136d-631e-49e0-8de4-e2e885014ef9.png)

**Comment by luc-languagetools** [comment]
Should be fixed in AwesomeTTS 1.74.

**Comment by Benjamin-Watson0** [comment]
I will look forward to him.
