### ISSUE TITLE
Naver Papago stopped working

### ISSUE THREAD

**Issue by Eltaurus-Lt** [AwesomeTTS/awesometts-anki-addon#297]
I started to receive this error whenever I try to use TTS:
```
got status_code 403 from https://papago.naver.com/apis/tts/makeID: b'{"code":"00002","message":"HMAC_HASH_INCORRECT","displayMessage":"HMAC_HASH_INCORRECT"}' 
```
It seems to happen with all Naver Papago voices/languages

**Comment by luc-languagetools** [comment]
Should be fixed now.

**Comment by Eltaurus-Lt** [comment]
Seems to work again fine.
Thank you for the fix.

**Comment by luc-languagetools** [comment]
If you feel satisfied with my service, please leave a review https://ankiweb.net/shared/info/1436550454
