### ISSUE TITLE
read revealed text only on backside of card?

### ISSUE THREAD

**Issue by smh020** [AwesomeTTS/awesometts-anki-addon#3]
is there a way to make it so that awesometts only reads the clozed text answer on the backside? I noticed it is available for on the fly reading, but not for mass creation of notes from the browser window. I do not want the front to be read nor the rest of the text on the backside/answer. I believe that auditory reinforcement of the tested material is beneficial to increased exposure and repetitions of the material. Thanks in advance

**Comment by felixraumann** [comment]
I think this is hard because a note can have multiple cloze, you can't know in advance which one will be hidden
