### ISSUE TITLE
How to add audio next to the highlighted text instead of at end of field?

### ISSUE THREAD

**Issue by slabzzz** [AwesomeTTS/awesometts-anki-addon#302]
I often notice that whenever I add audio, the audio file is put at the end of the field. Is there any way I can have the audio file text be put right next to the highlight instead?

**Comment by luc-languagetools** [comment]
I thought this worked and I remembered putting in a fix for that some time ago. Can you help describe your use case ? Are you trying to add audio only for specific words within a sentence in the field ?

**Comment by slabzzz** [comment]
> I thought this worked and I remembered putting in a fix for that some time ago. Can you help describe your use case ? Are you trying to add audio only for specific words within a sentence in the field ?

I want to order the audio files well. 

Say I have a field:

test

[audio file 1]

I highlight "test" for pronunciation. However, the field becomes:

test

[audio file 1]
[audio file 2 (the new "test" audio)]

This makes the audio file 1 play first when I intended for "test" to play first. So I have to move audio file 2 above audio file 1.

**Comment by luc-vocab** [comment]
consolidating with issue #271

**Comment by luc-vocab** [comment]
@slabzzz what's your operating system ?

**Comment by slabzzz** [comment]
MacOS Ventura 13.3.1

**Comment by slabzzz** [comment]
> @slabzzz what's your operating system ?

macos ventura 13.3.1

**Comment by luc-vocab** [comment]
OK, this issue is still puzzling me, no matter what I do, i can never get the audio tag to appear in front of the field
