### ISSUE TITLE
Naver Papago HMAC_HASH_INCORRECT

### ISSUE THREAD

**Issue by caball01** [AwesomeTTS/awesometts-anki-addon#307]
This looks to be the same issue as #297 which was fixed Jul 25. I started receiving the error yesterday (Nov 28, 2023).

The 1 note you selected has been processed. During processing, no notes were successfully updated.

The following problem was encountered:
got status_code 403 from https://papago.naver.com/apis/tts/makeID: b'{"code":"00002","message":"HMAC_HASH_INCORRECT","displayMessage":"HMAC_HASH_INCORRECT"}' (1 time)

The following note(s) have failed:
'bicicleta',

**Comment by luc-languagetools** [comment]
Should be fixed in the latest AwesomeTTS.

**Comment by caball01** [comment]
I was able to update my backlog of cards successfully with no errors. Thanks!
