### ISSUE TITLE
Separating packages: TTS file generation, and anki-specific code

### ISSUE THREAD

**Issue by jzohrab** [AwesomeTTS/awesometts-anki-addon#320]
Hello, AwesomeTTS is an awesome piece of work.  I was wondering if you had any thoughts on somehow extracting the code that does the service lookups from the Anki-related code, with a separate awesomeTTS package.

My reason for asking: I wrote [Lute](https://github.com/LuteOrg/lute-v3), software for learning languages through reading.  Lute's written in Python.  A common need for some languages is to get audio for words, so this feels like a natural overlap with AwesomeTTS.  You've already done super work about a top-level abstraction over the various services, I would prefer to not duplicate this effort if possible!

I'd be happy to help define or contribute to the work as needed.  I appreciate that this could be a sizeable undertaking!!  Maybe other Lute user/devs would be interested as well.

(The related Lute issue is https://github.com/LuteOrg/lute-v3/issues/36 )

Cheers and regards, jz

**Comment by luc-vocab** [comment]
Get in touch with me luc@vocab.ai I will give you some advice on the topic.
