### ISSUE TITLE
Support for Cambridge dictionary

### ISSUE THREAD

**Issue by woj-tek** [AwesomeTTS/awesometts-anki-addon#35]
It would be great if Awesome-TTS supported Cambridge Dicrionary - imho it has the best voice sample for British English (link: https://dictionary.cambridge.org/)

**Comment by kodi991** [comment]
I second that!

**Comment by omega3** [comment]
There is a commit for Cambridge. Works for me:

https://github.com/AwesomeTTS/awesometts-anki-addon/pull/65

https://github.com/AwesomeTTS/awesometts-anki-addon/pull/65/commits/44293133b5ed7be87bd20d3578d8dab92cea01b2

Just edit two files (changes in green color) and add one file. Be aware of the different paths.

**Comment by lucwastiaux** [comment]
Cambridge should be working on v1.15: https://ankiweb.net/shared/info/1436550454
