### ISSUE TITLE
Cloze deleted text not getting substituted properly

### ISSUE THREAD

**Issue by hjorthjort** [AwesomeTTS/awesometts-anki-addon#36]
Steps to reproduce:

1. Open Tools > AwesomeTTS... > "Text" tab
2. In "Handling text from a **Note** Field" section, for option "For a braced cloze marker", choose "replace w/ deleted text"
3. Click OK to save settings.
4. Open a card with Cloze deletion in note editor 
5. Highlight text with a braced close marker (such as "Hello, {{c1::world}}!").
6. Open AwesomeTTS by clicking the AwesomeTTS icon.

**Expected behavior:**
Preview field shows "Hello, world!"

**Actual behavior:**
Preview field shows "Hello, c!"

Awesome TTS version: master (2018-02-21)
Anki version: 2.1.0beta29
Qt version: Qt 5.10.0 PyQt 5.9.2

**Comment by picsi** [comment]
Relates to https://github.com/AwesomeTTS/awesometts-anki-addon/issues/9

**Comment by krassowski** [comment]
Thank you @hjorthjort. I will now close this issue as your fix was just merged into the master. Thanks again and happy new year!
