### ISSUE TITLE
"[Errno 2] Unable to find lame to transcode the audio." - even though lame is installed

### ISSUE THREAD

**Issue by kristofferR** [AwesomeTTS/awesometts-anki-addon#38]
AwesomeTTS can't find lame anymore:
> [Errno 2] Unable to find lame to transcode the audio. It might not have been installed.

 It worked fine in Anki 2.0, but not in Anki 2.1 with the current repo installed through install.sh. Running lame in Terminal works fine, lame is installed with Homebrew.

**Comment by CarlosEvo** [comment]
Same issue here, really annoying...

**Comment by CarlosEvo** [comment]
@kristofferR 
So I did some digging, and I found that changing line 75-76 of `service/base.py` to 

```python
# where we can find the lame transcoder
CLI_LAME = '/usr/local/bin/lame'
```

actually works. Somehow anki/awesometts is not loading `$PATH` correctly. I will leave it to the devs to resolve.

**Comment by AaronWrdo** [comment]
Same problem!
I did exactly what you said and got an error like this:
(Lame is installed and worked successfully in terminal, and the path is right.)
> 
> The following problem was encountered:
> [Errno 13] Permission denied: '/usr/local/Cellar/lame' (1 time)

How can I fix it?

> @kristofferR
> So I did some digging, and I found that changing line 75-76 of `service/base.py` to
> 
> ```python
> # where we can find the lame transcoder
> CLI_LAME = '/usr/local/bin/lame'
> ```
> 
> actually works. Somehow anki/awesometts is not loading `$PATH` correctly. I will leave it to the devs to resolve.
