### ISSUE TITLE
Oxford service stopped working

### ISSUE THREAD

**Issue by woj-tek** [AwesomeTTS/awesometts-anki-addon#4]
Currently it returns:

`<urlopen error [Errno 8] _ssl.c:507: EOF occurred in violation of protocol>`

**Comment by felixraumann** [comment]
I think this is because the ssl anki uses is old (anki is still python 2.7)
I think this can't be fixed by the addon.

**Comment by woj-tek** [comment]
I read a bit about it and if I'm not mistaken latest release of python2.7 has it fixed (Python 2.7.13, 2016-12-17) but Anki is build with older version (2.7.9-ish?). Could building Anki with newer version solve the issue?

At any rate - ignoring SSL errors wouldn't work?

**Comment by GarrisonBaird** [comment]
Same issue [here](/finalion/WordQuery/issues/41)
The connection is rejected at server side, there's no acceptable workaroud _(yes we do have some but too complicated)_, unless built-in python supports newest TLS protocols
**I think the best way to get to it, is reporting to Anki, asking them to upgrade built-in python**

**Comment by lucwastiaux** [comment]
Oxford is working now, and i've added some automated tests. Thank you @woj-tek , @GarrisonBaird
