### ISSUE TITLE
Integrating Watson's text to speech

### ISSUE THREAD

**Issue by ChristianKleineidam** [AwesomeTTS/awesometts-anki-addon#40]
https://www.ibm.com/watson/services/text-to-speech/ provides a text-to-speech engine that's free for 10,000 Characters per Month and for many AwesomeTTS users that can be enough to be productive.

**Comment by lucwastiaux** [comment]
The speech output looks to be high quality and doesn't look like it requires any particular python modules. So this is a good candidate.

**Comment by Grelo4ka** [comment]
I fully agree, it looks like their voices are much higher quality than the current ones.

**Comment by lucwastiaux** [comment]
Added in AwesomeTTS v1.28.
