### ISSUE TITLE
How to specify pronunciations?

### ISSUE THREAD

**Issue by bigsmile01** [AwesomeTTS/awesometts-anki-addon#43]
I am using Mac OS Speech Synthesizer as a voice.

I would like it so it ignores * symbols in my fields (Rather than reading them out as "Asterix").
I would also like it so it reads out "LIT" as lit (rather than L-I-T).

How can I do this?

I have clicked on AwesomeTTS > TEXT and added rules so to change how it reads * & LIT, but it seems to ignore the rules I have set up.

**Comment by lucwastiaux** [comment]
Can you give me an exact example, tell me what you get, and what you expect ?

**Comment by bigsmile01** [comment]
Example, my card has "LIT:"

What I get: the voices says L - I - T (e.g. it reads out each letter separately)
What I expect: "Lit"(e.g. short for literal)

**Comment by lucwastiaux** [comment]
is "LIT:" really the only content of the field on that card ? Or is it part of a larger sentence ? If so, can you give me that full sentence ?

**Comment by bigsmile01** [comment]
> is "LIT:" really the only content of the field on that card ? Or is it part of a larger sentence ? If so, can you give me that full sentence ?

Here are some examples:
LIT: You can walk about this road
LIT: Ah, “Must study hard”, it’s a bad act, isn’t it.
LIT: I hope with yearning, Thanksgiving

**Comment by lucwastiaux** [comment]
I've tested a few services which seem to correctly pronounce _LIT_ and not _L, I, T_. I used the following sentence:  _LIT: You can walk about this road_

- Naver translate (english)
- Oddcast (Allison female en-US)
- Microsoft Azure (JessaNeural en-US)
- Google Cloud TTS (en-US-Wavenet-D)

Is this an option for you, or are you set on using the MacOS speech synthethizer?

**Comment by bigsmile01** [comment]
It would be neat if it worked with OS, but these other ones will do fine. Thanks for your help!
