### ISSUE TITLE
Already downloaded audio file not reused

### ISSUE THREAD

**Issue by szpak** [AwesomeTTS/awesometts-anki-addon#46]
In one deck I have English words to learn. In another a subset of those words in a card type with typing answer. I would expect to have old audio files generated using the same engine (for the original deck) to be reused for the new one. However, AwesomeTTS downloads it again creating a file with the same name, however with " (1)" at the end. It would be probably safe to just reuse old file (from the same engine) by default.

I'm not sure which version of AwesomeTTS I have (how can I check it?). The files have date V 2017. Anki 2.0.50.

**Comment by krassowski** [comment]
The version should be written in the right-top corner of the configuration window:
![screenshot from 2018-05-21 22-09-07](https://user-images.githubusercontent.com/5832902/40327547-a8270eb0-5d43-11e8-80fb-fa71a02103ab.png)

**Comment by krassowski** [comment]
Are all the options for set for the engine the same across the decks?

**Comment by szpak** [comment]
Rather yes (assuming your are talking about the "Add audio to selected" dialog). The new check uses the same card type (just with an extra input text). The output name is the same - just " (1)" is added at the end. I use Oddcast.

AwesomeTTS v1.11.0 :).

**Comment by lucwastiaux** [comment]
how impactful is this issue ?

**Comment by szpak** [comment]
Not much. Unless you have a lot of duplicates.

I will close it, you probably have a number of more important things to handle. Maybe it even doesn't occur in 2020. I will check with the new version.
