### ISSUE TITLE
有谁知道如何设置代理么？我的插件无法访问谷歌

### ISSUE THREAD

**Issue by tooyond** [AwesomeTTS/awesometts-anki-addon#47]
只能使用百度，百度的发音又怪怪的

**Comment by CarlosEvo** [comment]
[Anki Manual#Proxies](https://apps.ankiweb.net/docs/manual.html#proxies)

虽然谷歌的（德语）发音也不怎么样就是了
Although Google's TTS does not sound prestine either.

**Comment by lucwastiaux** [comment]
What about Youdao ? which voice are you trying to access ?
