### ISSUE TITLE
Anki 2.1 issue with new cards. 

### ISSUE THREAD

**Issue by lucaswobeto** [AwesomeTTS/awesometts-anki-addon#54]
Hello community, I recently upgraded my Anki to 2.1 and now when I'm adding a new card and try to use AwesomeTTS, it doesn't select the text on the field i'm writing on but from the clipboard. I don't know if it's a bug or it's supposed to be this way from now on, someone know how to fix it?
Sorry for my english

**Comment by staticdev** [comment]
Please +1 for Anki 2.1.

**Comment by bluepurplegreen** [comment]
Awesome work Lucas, this is the killer-app for Anki. It needs porting to 2.1!

**Comment by hugoforte** [comment]
Would love for it to get to 2.1!
