### ISSUE TITLE
Duplicate audio plays from previous card and THEN plays appropriate audio

### ISSUE THREAD

**Issue by chrishollandaise** [AwesomeTTS/awesometts-anki-addon#55]
It's quite annoying, I tinkered around with the TTS settings and the audio-replay settings on the deck themselves, however nothing seems to fix the problem. I then thought it could possibly be the audio files themselves, but I checked it and they played the correct audio. So I don't really know whats going on please help.

**Comment by lucwastiaux** [comment]
What operating system do you use ? Is your audio generated into sound files ? 
I believe what you're describing is an Anki problem, not specific to AwesomeTTS. As you mentioned yourself, the audio files are correct.
