### ISSUE TITLE
Error in generator.py

### ISSUE THREAD

**Issue by charlesoblack** [AwesomeTTS/awesometts-anki-addon#6]
```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons\awesometts\router.py", line 958, in _on_worker_signal
    self._threads[thread_id]['callback'](exception)
  File "C:\Users\User\AppData\Roaming\Anki2\addons\awesometts\router.py", line 545, in completion_callback
    callbacks['okay'](human(path))
  File "C:\Users\User\AppData\Roaming\Anki2\addons\awesometts\router.py", line 295, in on_okay
    callbacks['okay'](path)  # n.b. self() below handles want_human
  File "C:\Users\User\AppData\Roaming\Anki2\addons\awesometts\gui\generator.py", line 347, in okay
    filename = self._browser.mw.col.media.addFile(path)
AttributeError: 'NoneType' object has no attribute 'media'
```

I got this error while generating sound files. Anki version 2.0.44, Qt 4.8.4 PyQt 4.10. AwesomeTTS version 1.11.0. I was generating from a custom group that includes Google Translate (ja), NAVER Translate (ja), NeoSpeech(Ryo). After the error popped up I am able to close the error screen but ATTS hangs and Anki, since it's waiting for ATTS to respond, hangs as well.

**Comment by felixraumann** [comment]
what other addons do you have?

**Comment by charlesoblack** [comment]
autosync, ankihabitica, awesomeTTS (obviously), button_colours_good_again, FEN chess visualizer, learning achievements (cumulative count for mature/learning cards), memrise course importer, more overview stats 2, night mode, power format pack, puppy reinforcement, remove study ahead penalty, review heatmap, _If_ tag .

I can find you the links to them on the anki website, if you need.

**Comment by charlesoblack** [comment]
Any update on this?
