### ISSUE TITLE
tag tts generated by JS can't play

### ISSUE THREAD

**Issue by MerliniKing** [AwesomeTTS/awesometts-anki-addon#60]
For some reasons I have to generate tts tag by JS code in anki note, but it can't play audio totally.So I want to know is there any method to trigger tts tag in JS code?

**Comment by lucwastiaux** [comment]
@MerliniKing can you describe your use case in more detail ? Please include a detailed example:

- what's the source data in your card
- what does the JS code do
- what is the final output

**Comment by lucwastiaux** [comment]
closed for inactivity, feel free to re-open if necessary
