### ISSUE TITLE
NAVER Translate doesn't work

### ISSUE THREAD

**Issue by emanuelcerqueira** [AwesomeTTS/awesometts-anki-addon#61]
Request got text/html instead of audio/mpeg

![image](https://user-images.githubusercontent.com/25643113/50716894-a30eb400-1062-11e9-9f88-fc2d6f10ae50.png)

**Comment by krassowski** [comment]
Thanks for reporting this. I can confirm that there is an issue with NAVER Translate service.

**Comment by krassowski** [comment]
It looks that NAVER Translate does not exist any longer. It was replaced by NAVER Papago which offers a [translation API](https://developers.naver.com/docs/nmt/reference/) (which require registration to get keys) but I do not see anything on TTS API.

**Comment by krassowski** [comment]
Found it, it's called NAVER Clova Speech Synthesis now and the keys can be purchased at [ncloud.com/product/aiService/css](https://www.ncloud.com/product/aiService/css). A new service to support Clova needs to be writtten but it should be fairly simple as they provide a nice REST API.

**Comment by Magneticdud** [comment]
Can just update the naver service to use the new papago?

I saw it sends via POST this string similar to a json:

`UC,Uzdpitch":0,"speaker":"yuri","speed":0,"text":"幾分"}`

(probably something wrong with the first bytes of base64?)

encoded in base64 to https://papago.naver.com/apis/tts/makeID

which answers with another JSON:

`{"id":"1.10.9_2815-1315b8318932e75896c1b070a03dd961-1546806478016"}`

then the mpeg is downloaded from:

https://papago.naver.com/apis/tts/1.10.9_2815-1315b8318932e75896c1b070a03dd961-1546806478016

**Comment by Pet20q** [comment]
Any news on the fix?

**Comment by Magneticdud** [comment]
The fix works great on chinese words, but gives "error 501 not implemented" on chinese sentences. Is this normal? 

Because I sniffed the traffic on papago.naver.com and the server responds with a single mpeg audio file, not many single audio fragments joined together by the client

**Comment by YOnoda** [comment]
@aquach That triggered an error - *The following problem was encountered:
a bytes-like object is required, not 'str'* when generating the audio.
