### ISSUE TITLE
Neospeech audio is too fast

### ISSUE THREAD

**Issue by alluria** [AwesomeTTS/awesometts-anki-addon#68]
Hello. I would like to to slow down Misaki's voice from Neospeech because is too fast for me, and there is an option to change the speed in Neospeech's site. I know this isn't a problem of AwesomeTTS, but anyway is there a way of changing Neospeech audio speed?

**Comment by lucwastiaux** [comment]
Neospeech is currently broken :(

**Comment by lucwastiaux** [comment]
Closing for now, not enough demand.
