### ISSUE TITLE
is it possible to add Forvo?

### ISSUE THREAD

**Issue by Troyciv** [AwesomeTTS/awesometts-anki-addon#7]
Is it possible to use Forvo.com as a source, when I have an api key?

**Comment by Dador** [comment]
Take a look at pull request #10.

**Comment by lucwastiaux** [comment]
Forvo has been added in release v1.16, looking for volunteers to test the addon (grab the .ankiaddon file) before I release it on AnkiWeb: https://github.com/AwesomeTTS/awesometts-anki-addon/releases/tag/v1.16.0
