### ISSUE TITLE
bing English Great Britain male voice

### ISSUE THREAD

**Issue by omega3** [AwesomeTTS/awesometts-anki-addon#71]
Is it possible to add 
https://www.bing.com/translator
English Great Britain male voice?

In my opinion it sounds far more natural and more fluent / flowing / smooth than google voice. Just give it a try and compare a few sentences.

This might be useful:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-python-text-to-speech

https://docs.microsoft.com/pl-pl/azure/cognitive-services/speech-service/quickstart-python-text-to-speech

And these scripts (but they don't work for me):
https://github.com/westparkcom/Python-Bing-TTS

https://github.com/davrous/BingSpeech

**Comment by woj-tek** [comment]
Actually all voices would be nice - I just checked it for a couple of languages and they sound quite good.

**Comment by omega3** [comment]
This can be used
https://github.com/soimort/translate-shell

It can download audio to a file from Bing.
https://github.com/soimort/translate-shell/issues/129

By the way, is this project alive? Has it something to do with:
https://ankiweb.net/shared/info/2139632824

**Comment by omega3** [comment]
Bing changed its API. Only 30 days free trial is available. So, it is invalid request.
