### ISSUE TITLE
Duplicate menu and sound icon in Anki 2.1.x

### ISSUE THREAD

**Issue by ikey4u** [AwesomeTTS/awesometts-anki-addon#72]
Hi, thank you for your awesome work for Anki.

I have tried to install this plugin for anki 2.1, but it appears two duplicate menu entries in Anki menus, showed as below:

![image](https://user-images.githubusercontent.com/12681575/55808884-88435400-5b17-11e9-920d-043856260e99.png)

![image](https://user-images.githubusercontent.com/12681575/55808931-9b562400-5b17-11e9-896f-80f436e2bb51.png)

![image](https://user-images.githubusercontent.com/12681575/55808964-aa3cd680-5b17-11e9-8b9a-f4eec56b8af9.png)

I have some researches on the source codes, but I have no idea about where is wrong.

Would you please to do some bugs fixing for this issue?

**Comment by Spenhouet** [comment]
I can confirm this for windows:

![image](https://user-images.githubusercontent.com/7819068/56161776-b66add00-5fca-11e9-9258-5e211a855b50.png)

![image](https://user-images.githubusercontent.com/7819068/56161846-e0240400-5fca-11e9-8539-d28cb2fc3ce4.png)

![image](https://user-images.githubusercontent.com/7819068/56161882-f92cb500-5fca-11e9-8e0f-e4fd64121253.png)

![image](https://user-images.githubusercontent.com/7819068/56161925-12cdfc80-5fcb-11e9-8776-245646dccb89.png)

**Comment by nathanielburbank** [comment]
I can confirm this is happening on OS X as well. I'm getting duplicate menu items, duplicate buttons, and most annoyingly, duplicate playback on my cards. (This is running Anki 2.1.12, and 1.13-dev of Awesome TTS -- the latest version listed in the 2.1 add-on directory).

**Comment by ch-sa** [comment]
Can confirm this also for Linux (Linux Mint 19.1 + AwesomeTTS for Anki 2.1 `427598962`). Still great tool, thank's a lot!

![grafik](https://user-images.githubusercontent.com/26072175/58952957-68d24b80-8795-11e9-9657-ee3566b0c9c8.png)

**Comment by lovac42** [comment]
Silly question, but you guys wouldn't happen to have two copies of the same addon by different authors would you?

![image](https://user-images.githubusercontent.com/42665127/61431375-49355380-a8fb-11e9-9f00-974e2a73c3db.png)
![image](https://user-images.githubusercontent.com/42665127/61431395-505c6180-a8fb-11e9-99a3-93a95dd5c543.png)
![image](https://user-images.githubusercontent.com/42665127/61431383-4c304400-a8fb-11e9-9708-46ff214e7301.png)
![image](https://user-images.githubusercontent.com/42665127/61431398-52262500-a8fb-11e9-8d41-036fef96a09e.png)


![image](https://user-images.githubusercontent.com/42665127/61431527-c52f9b80-a8fb-11e9-96e6-d63128dcf949.png)

**Comment by p2635** [comment]
@lovac42 nope, only one.

**Comment by lovac42** [comment]
This is a specific problem related to addon number 427598962. The lastest update on ankiweb is packaged incorrectly causing the addon to be loaded twice on startup. It is not related to the other forks.

**Comment by p2635** [comment]
thans @lovac42 , so is the solution to go for this one instead? https://ankiweb.net/shared/info/2139632824. I can't even tell which entry is the correct one anymore. If 427598962 is wrong, does that page belong to you? Can you take it down and put up a proper page?

**Comment by lovac42** [comment]
@p2635 I am not the maintainer of that addon and he seems to have disappeared. All the versions currently on Ankiweb have minor bugs here and there, so just try your luck and see which one works better for your system. I suggest trying the one by Nickolay https://ankiweb.net/shared/info/814349176

**Comment by p2635** [comment]
Thanks @lovac42, it's kind of sad that they randomly disappeared, I left a message on #69 and hope that they come back. If not, I will check out Nickolay's version and perhaps help whichever project is the latest.
