### ISSUE TITLE
NeoSpeech error - 'set-cookie'

### ISSUE THREAD

**Issue by Spenhouet** [AwesomeTTS/awesometts-anki-addon#73]
I just installed the AwesomeTTS addon to add audio to my Japanese learning cards.
From the internet I did read that NAVER and NeoSpeech are the only TTS services that provide a good Japanese text to speech.

Since NAVER currently doesn't work (#61) I wanted to try NeoSpeech but I also couldn't get it to work.

I'm always getting a error message saying:

> Cannot preview the input phrase with these settings.
> 
> 'set-cookie'

See screenshot below.
Not sure what setting I'm expected to set?
 
![image](https://user-images.githubusercontent.com/7819068/56160647-ff6d6200-5fc7-11e9-9387-87c5a14b77e3.png)

**Comment by Spenhouet** [comment]
Oh... its in the update note:

> * NOTE: This update makes NeoSpeech service not work. We will try to fix this in the next update.

I will leave it open to track this issue.

**Comment by Waog** [comment]
Same Problem with NeoSpeech for Chinese

**Comment by toxinon** [comment]
NeoSpeech URL has changed into ReadSpeaker.com

It seems the files are obtained by mean of a simple-proxy.php request  using the demo button form

Any progress on this? Python code is so kryptik to me

**Comment by lovac42** [comment]
I messed around with it but it has that "this is a demo" inserted into every audio clip.
https://github.com/lovac42/awesometts-CCBC-addon/blob/neospeech/awesometts/service/neospeech.py

**Comment by lucwastiaux** [comment]
@Spenhouet Naver japanese voice should be fixed now in v1.15. You can download it here: https://ankiweb.net/shared/info/1436550454

**Comment by lucwastiaux** [comment]
@lovac42 thanks for giving this a try. I also get "this is a demo" back. Unless someone has an idea, I don't think we can fix it. Naver and other services have japanese, are these an acceptable substitute ? Google Cloud TTS also has a good japanese voice, you could try it using one of the free keys (https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Google-Cloud-Text-to-Speech)
