### ISSUE TITLE
Awesome TTS - Oddcast not working help!

### ISSUE THREAD

**Issue by trevdoggo** [AwesomeTTS/awesometts-anki-addon#74]
Hi there, I'm a mac user using Anki Version 2.0.52 and thus using the older version of AwesomeTTS. The Thai voices with Oddcast are phenomenal, however I'm not able to record for some reason.

When I try to record using Oddcast I receive this error message(see below).  Any idea how I can fix this??? 

Thanks to anyone reading my post.

Cannot preview the input phrase with these settings.

<urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>

![awesomeTTS](https://user-images.githubusercontent.com/51141167/58520303-02817380-816c-11e9-9268-e1e941265f87.png)

**Comment by flaviolc18** [comment]
any update?????

**Comment by trevdoggo** [comment]
Unfortunately not, and I’m not a developer. If you hear of any fix to this problem can you comment back here? Thanks

**Comment by lucwastiaux** [comment]
@flavluc @trevdoggo Oddcast for Thai with the Narisa voice seems to work in v1.15. I added an automated test case for this combination. Can you try installing v1.15 ? https://ankiweb.net/shared/info/1436550454
