### ISSUE TITLE
create audio file for multiple fields

### ISSUE THREAD

**Issue by Troyciv** [AwesomeTTS/awesometts-anki-addon#8]
When selecting multiple cards in the card browser and trying to 'add audio to selected' I can only select one field at a time. It would be great if the user could select multiple fields at once.

**Comment by lucwastiaux** [comment]
Can you describe your use case a bit more ? it feels like you could just achieve this with two calls of AwesomeTTS, even if you needed to do it on 1000s of cards, it wouldn't really take long at all ?
