### ISSUE TITLE
AwesomeTTS is causing my Mac to stop playing any audio

### ISSUE THREAD

**Issue by hazembergg** [AwesomeTTS/awesometts-anki-addon#80]
Please help! I can't seem to figure out what is the cause. 

Ever since I installed this AwesomeTTS, when I flip throw my decks of card [using auto-flip, auto-rate 'good' add-on], it works fairly well.

A little over 30 minutes and the cards keep flipping but the audio just stops playing - and not just on 
Anki... on all over my computer! My browser loads YT video but don't play them, my Quicktime doesn't play anything, iTunes.... etc all suddenly stops!

The only way to get my audio back is to restart my computer

Any thoughts what is the cause of that?
=========
Running on MacCatalina 
Anki 2.1 
My deck is 5000 words automatically flipping every 3 seconds, could this be the cause of the bug?

**Comment by lucwastiaux** [comment]
How are you generating the speech sounds ? Do you generate ahead of time by having AwesomeTTS add a sound file to your deck, or do you use the <tts> tag to generate on the fly ?

**Comment by lucwastiaux** [comment]
closed for inactivity, feel free to re-open if necessary
