### ISSUE TITLE
Cannot preview the input phrase with these settings. Request got audio/mpeg Content-Type for web request; wanted binary/octet-stream

### ISSUE THREAD

**Issue by liwenjing93** [AwesomeTTS/awesometts-anki-addon#82]
Hi, I am using anki 2.1 and I can't use TTS to generate sound with Oxford dictionary. I can do it with Google translate but oxford. Anyone can help me about this? Thanks 

---------------------------

Cannot preview the input phrase with these settings.

Request got audio/mpeg Content-Type for web request; wanted binary/octet-stream

---------------------------

![image](https://user-images.githubusercontent.com/9654732/69417892-23f29f00-0d4c-11ea-9864-3fcb82228e53.png)

**Comment by AntoineQ1** [comment]
Issue solved :
Please replace `require=dict(mime='binary/octet-stream', size=1024),` to `require=dict(mime='audio/mpeg', size=1024),` in 814349176\awesometts\service\oxford.py

**Comment by liwenjing93** [comment]
> Issue solved :
> Please replace `require=dict(mime='binary/octet-stream', size=1024),` to `require=dict(mime='audio/mpeg', size=1024),` in 814349176\awesometts\service\oxford.py
> 
> I started a pull request : #90

Thank you, but can you tell me details where the file **oxford.py** is? I could not find it in **C:\Program Files (x86)\Anki**  and can not find it in the Anki software. I am using anki 2.0 :) 

![image](https://user-images.githubusercontent.com/9654732/78543765-598fb480-7823-11ea-9a29-68c7cb9105bc.png)

**Comment by AntoineQ1** [comment]
Ok, I arrived on the software a week ago, I didn't even know Anki 2.0 ;-)

> A fairly simple and universal way is to go to the list of plugins, choose AwesomeTTS and click on Show Files.
> Or you can manually search in **%appdata%**.
> For example, the path may be : **C:\Users\\{YOUR_USERNAME}\AppData\Roaming\Anki2\addons21\814349176\awesometts\service**

Tell me if it works for you !

**Comment by liwenjing93** [comment]
> Ok, I arrived on the software a week ago, I didn't even know Anki 2.0 ;-)
> 
> > A fairly simple and universal way is to go to the list of plugins, choose AwesomeTTS and click on Show Files.
> > Or you can manually search in **%appdata%**.
> > For example, the path may be : **C:\Users\{YOUR_USERNAME}\AppData\Roaming\Anki2\addons21\814349176\awesometts\service**
> 
> Tell me if it works for you !

OH MY GOD, you saved my life. At first, I barely believe that it will work, but for now it's working well. Thank you very much!!!  <3

-------------------------------------------

I will attach some Screenshots in case someone low tech needs them:

![Screenshot_2](https://user-images.githubusercontent.com/9654732/79044453-68b1a080-7c2f-11ea-8915-8151f6e5808a.jpg)


![Screenshot_1](https://user-images.githubusercontent.com/9654732/79044436-5899c100-7c2f-11ea-871b-d6e1235568a3.jpg)

**Comment by AntoineQ1** [comment]
Yes, I also doubted that such a simple modification would solve the problem in the first place ;-)

Glad it works, and good learning on Anki :D

**Comment by lucwastiaux** [comment]
Thank you @AntoineQ1 , @kelciour . I've added an automated test for Oxford.
