### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by omega3** [AwesomeTTS/awesometts-anki-addon#84]
AwesomeTTS for Anki 2.1 updated again
https://ankiweb.net/shared/info/2139632824
I don't know what version is this and if the author is the same as for original version.

After update to 2.1.17 on Linux I have error:

```
When loading 'AwesomeTTS for Anki 21 updated again':

Traceback (most recent call last):
  File "aqt/addons.py", line 97, in loadAddons
  File "/home/user/.local/share/Anki2/addons21/2139632824/__init__.py", line 42, in <module>
    from . import awesometts  # noqa, pylint:disable=wrong-import-position
  File "/home/user/.local/share/Anki2/addons21/2139632824/awesometts/__init__.py", line 37, in <module>
    from .router import Router
  File "/home/user/.local/share/Anki2/addons21/2139632824/awesometts/router.py", line 335
    want_human=False, note=None, async=True):
                                 ^
SyntaxError: invalid syntax
```
With Anki 2.1.15 I didn't have this error.

Version 2.1.17 (c69ccb50)
Python 3.8.1 Qt 5.14.0 PyQt 5.13.2

Operating System: Manjaro Linux 
KDE Plasma Version: 5.17.4
KDE Frameworks Version: 5.65.0
Qt Version: 5.14.0
Kernel Version: 5.4.6-2-MANJARO
OS Type: 64-bit

**Comment by zoenglinghou** [comment]
I have the same issue. `flake8` suggested that `async` is reserved since python 3.7.

I am on macOS, so I doubt Anki is going to use my system's python distrubution, albeit I just upgraded to python 3.8.

Renaming the keyword works for me.

**Comment by omega3** [comment]
Thank you very much. Works for me as well.

**Comment by johan456789** [comment]
If it's fixed already why it's not updated [here](https://ankiweb.net/shared/info/427598962)?
