### ISSUE TITLE
An unhandled exception occurs

### ISSUE THREAD

**Issue by helperman** [AwesomeTTS/awesometts-anki-addon#88]
Try to generate a sound of an english word and here is the error: 

> Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
> Platform: Windows 8.1
> Flags: frz=True ao=True sv=1
> Add-ons, last update check: 2020-03-17 22:32:27
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt\webview.py", line 30, in cmd
>   File "aqt\webview.py", line 96, in _onCmd
>   File "aqt\webview.py", line 422, in _onBridgeCmd
>   File "aqt\editor.py", line 377, in onBridgeCmd
>   File "C:\Users\temp1\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 121, in _show
>     self._instance = self._target.constructor(
>   File "C:\Users\temp1\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 667, in __init__
>     super(EditorGenerator, self).__init__(
>   File "C:\Users\temp1\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 243, in __init__
>     super(ServiceDialog, self).__init__(*args, **kwargs)
>   File "C:\Users\temp1\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 77, in __init__
>     super(Dialog, self).__init__(parent)
> RuntimeError: wrapped C/C++ object of type Browser has been deleted
>

**Comment by lucwastiaux** [comment]
same question, can you try the latest version (https://ankiweb.net/shared/info/1436550454) and let me know if it's still happening ?

**Comment by lucwastiaux** [comment]
closed for inactivity, feel free to re-open if necessary
