### ISSUE TITLE
Another unhandled exception happens during audio playback

### ISSUE THREAD

**Issue by helperman** [AwesomeTTS/awesometts-anki-addon#89]
> Error 
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
> If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
> When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
> Debug info:
> Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
> Platform: Windows 8.1
> Flags: frz=True ao=True sv=1
> Add-ons, last update check: 2020-03-20 10:34:16
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt\taskman.py", line 65, in _on_closures_pending
>   File "aqt\taskman.py", line 53, in <lambda>
>   File "aqt\sound.py", line 235, in <lambda>
>   File "aqt\sound.py", line 275, in _on_done
>   File "concurrent\futures\_base.py", line 432, in result
>   File "concurrent\futures\_base.py", line 388, in __get_result
>   File "concurrent\futures\thread.py", line 57, in run
>   File "aqt\sound.py", line 235, in <lambda>
>   File "aqt\sound.py", line 380, in _play
>   File "aqt\sound.py", line 261, in _wait_for_termination
> AttributeError: 'NoneType' object has no attribute 'returncode'
>

**Comment by lucwastiaux** [comment]
does this still happen with the latest version here ? https://ankiweb.net/shared/info/1436550454

**Comment by lucwastiaux** [comment]
closed for inactivity, feel free to re-open if necessary
