### ISSUE TITLE
Add-on Failed To Load

### ISSUE THREAD

**Issue by Mushakushi** [AwesomeTTS/awesometts-anki-addon#91]
I'm getting this error message everytime I open Anki. I'm using this link https://ankiweb.net/shared/info/427598962. 

> An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.
> 
> When loading 'AwesomeTTS for Anki 21 updated':
> Traceback (most recent call last):
> File "aqt/addons.py", line 205, in loadAddons
> File "/home/user/.local/share/Anki2/addons21/427598962/__init__.py", line 42, in <module>
> from . import awesometts # noqa, pylint:disable=wrong-import-position
> File "/home/user/.local/share/Anki2/addons21/427598962/awesometts/__init__.py", line 36, in <module>
> from .player import Player
> File "/home/user/.local/share/Anki2/addons21/427598962/awesometts/player.py", line 25, in <module>
> from .text import RE_FILENAMES
> File "/home/user/.local/share/Anki2/addons21/427598962/awesometts/text.py", line 35, in <module>
> RE_CLOZE_BRACED = re.compile(anki.template.template.clozeReg % r'\d+')
> AttributeError: module 'anki.template' has no attribute 'template'

**Comment by DeltraEcho** [comment]
https://ankiweb.net/shared/info/814349176

Try this one instead.

**Comment by Mushakushi** [comment]
It works
