### ISSUE TITLE
Collins French Dictionary

### ISSUE THREAD

**Issue by Artyom240** [AwesomeTTS/awesometts-anki-addon#92]
The problem is that i don't know what exactly to change to get french voice in the Collins dictionary. Please help me
![2020-04-26_15-23-15](https://user-images.githubusercontent.com/64360035/80307531-4e042d80-87d2-11ea-8a15-aafc4a755416.png)

**Comment by lucwastiaux** [comment]
Collins with french voice is working in v1.15, we even have an automated test for it. Can you try installing the latest (https://ankiweb.net/shared/info/1436550454) and trying again ?
