### ISSUE TITLE
Fix for Naver TTS

### ISSUE THREAD

**Issue by Clewhie** [AwesomeTTS/awesometts-anki-addon#95]
Naver doesn't work. Please consider updating naver.py file in your addon with this one: https://gist.github.com/eescueta/ca38d82c05b3f97ec704089425689025 Everything else works great, thank you for your work!

**Comment by lucwastiaux** [comment]
thank you, I will try to integrate this change after I get the travis CI build working again.

**Comment by lucwastiaux** [comment]
fixed in #79
