### ISSUE TITLE
how to add APP_KEY  &&  APP_SECRET , in youdao.py ,Post http request to my self  api  which subscribed from youdao.com

### ISSUE THREAD

**Issue by HillCat** [AwesomeTTS/awesometts-anki-addon#96]
I want'to modify the youdao.py ,to surpport MySelf Api , subscribe form openapi.youdao.com.  How to modify the youdao.py to add APP_KEY  &&  APP_SECRET,Thanks!

**Comment by lucwastiaux** [comment]
if I understanding correctly, you have an API key for youdao, and you'd like to use it on the service. This may require a development change, to make it easier, could you post a link to the documentation of the API ?

**Comment by lucwastiaux** [comment]
closed for inactivity, feel free to re-open if necessary
