### ISSUE TITLE
New AnkiWeb addon page

### ISSUE THREAD

**Issue by lucwastiaux** [AwesomeTTS/awesometts-anki-addon#98]
I've created a new AnkiWeb addon page: https://ankiweb.net/shared/info/1436550454

I understand in the short-term, this will create confusion within users. However this is the recommendation from Damien, he suggested I create a new version, and if it has a good track record of being maintained, it could become the official entry, and if other authors are willing, we could decommission other entries. For this to happen though, we have to show we can maintain this addon over a duration of time.

**Comment by woj-tek** [comment]
As commented in other issue:
> I created an issue in one of the forks that I use (that seemed to be the most working and compatible for me) asking it's developer @lovac42 to merge his work and contributing here: lovac42#8

Maybe this issue could be pinned to the top?
