### ISSUE TITLE
Audio from Duden can't be found

### ISSUE THREAD

**Issue by hy0merun** [AwesomeTTS/awesometts-anki-addon#99]
I tried the Duden feature with several simple German words and it never worked.

Error Message:
> Cannot preview the input phrase with these settings.
> 
> Duden does not have recorded audio for this word.

**Comment by lucwastiaux** [comment]
I can confirm it's broken, can you show me an example link to Duden and highlight on a screenshot where the audio for pronunciation can be found ? I couldn't find it from a quick search.

**Comment by hy0merun** [comment]
There you go.
Link:
https://www.duden.de/rechtschreibung/danke

The sound symbol is almost at the bottom of the page:
![Screenshot 2020-06-17 at 11 21 24](https://user-images.githubusercontent.com/67026243/84880352-b19d2f80-b08c-11ea-9d1b-6dcde7bfc143.png)

**Comment by lucwastiaux** [comment]
I just added a fix for Duden, can you give it a try ? I think it should work for simple words, but there may be more complex cases which will need additional logic.

**Comment by hy0merun** [comment]
I copied the Duden.py into my Anki folder and tried it out.
It finds sounds for many simple words now.
However, there are still a couple of issues:

1. When there are two words with the same spelling, it struggles finding the right one. For example: "Weg" (noun, English: way) and "weg" (adverb, English:"away") have different pronunciations. I hope I am not wrong, but right now your code takes the first match in the search and takes the sound file from it. 
I think you can fix it by distinguishing between words with capital letters and those without capital letters, because the first letter of the word is always capitalised in the German language. I think this is also how the previous code solved this problem.
2. People learn German nouns usually with one of the three articles "der" (for masculine), "die" (for feminine) and "das"(for neutral) to learn the gender of that noun. To come back to the example I mentioned above, "Weg" (English: way) is often written as "der Weg" in Anki. Right now, the program doesn't find the word anymore if there is an article in front or behind the actual word. 
3. There are quite a lot words on Duden.de which don't have an recorded audio on their page. It would be nice to have a dedicated error message for this case. Right now it says: "'NoneType' object is not subscriptable".

**Comment by lucwastiaux** [comment]
1. Agreed, the code shouldn't lowercase anything. let me try to fix it.
2. please provide some exact examples with expectations.
3. yes I can fix that.

**Comment by hy0merun** [comment]
Three different examples:

1. same spelling but lower case
Input: "das Können" OR "Können, das"
should lead to https://www.duden.de/rechtschreibung/Koennen
but **not** to https://www.duden.de/rechtschreibung/koennen
(same spelling but lower case)

2. same spelling but lower case, URL is not just "*/weg" as expected
Input: "der Weg" OR "Weg, der"
should lead to https://www.duden.de/rechtschreibung/Weg
but **not** to https://www.duden.de/rechtschreibung/weg_fort_abwesend_entfernt

3. Word begins with "Der", but it is part of the word itself so it shouldn't be stripped
Input: "Dermatologe" OR "der Dermatologe" OR "Dermatologe, der"
should lead to https://www.duden.de/rechtschreibung/Dermatologe

to be stripped strings are (including spaces):
If they are in front of the word: ["der ", "die ", "das "]
if they are behind the word: [", der", ", die", ", das"]

**Comment by hy0merun** [comment]
Additional case, that might cause an issue: (I found it by accident)
Input "weg"
should lead to https://www.duden.de/rechtschreibung/weg_fort_abwesend_entfernt
URL is not just "*/weg" as expected

**Comment by lucwastiaux** [comment]
I just committed a new version which fixes the article handling (before, after word). Please give it a try.  Also please check whether weg/Weg are acceptable from a pronunciation perspective.

**Comment by hy0merun** [comment]
Works fine now, thanks! Good job!

**Comment by lucwastiaux** [comment]
Thanks, it'll be included in the next release. Please add a rating on https://ankiweb.net/shared/info/1436550454 if you feel so inclined.

**Comment by hy0merun** [comment]
I already did yesterday ;)

**Comment by lucwastiaux** [comment]
I've released this change in 1.17: https://ankiweb.net/shared/info/1436550454 https://github.com/AwesomeTTS/awesometts-anki-addon/releases/tag/v1.17.0
